use crate::combine::{bond_strength,evaluate_formation,experimental_combine_work_cost,experimental_interaction,ExperimentalInteraction,FormationEvaluation};
use crate::contact::{connection_pair_candidates_cached,ConnectionCompatibilityCache};
use crate::resources::{BaseResource,Material,ResourceProperties};
use crate::structure::{Bond,OrganismStructure,Placement,StructuralUnit};
const COMBINE_CONTACT_TOLERANCE:f64=1.0;const EPSILON:f64=1e-12;
#[derive(Clone,Copy,Debug,PartialEq)]pub struct StructuralCombineResult{pub unit_a:usize,pub unit_b:usize,pub point_a:usize,pub point_b:usize,pub interaction:ExperimentalInteraction,pub work_cost:f64,pub formation_threshold:f64,pub investment:f64,pub surplus:f64,pub bond_strength:f64,pub bond_energy:f64,pub bond_index:usize}
#[derive(Clone,Copy,Debug,PartialEq,Eq)]pub enum StructuralCombineError{MissingUnit,NoGeometricallyEligibleCandidate,NonFiniteInvestment,InsufficientInvestment,NonFiniteWorkCost,NonFiniteBondStrength,BondGeometryRejected,UnfavorableInteraction}
pub(crate)fn required_investment(a:ResourceProperties,b:ResourceProperties,e:FormationEvaluation,water:f64)->Result<(ExperimentalInteraction,f64,f64),StructuralCombineError>{let i=experimental_interaction(a,b,e.candidate,water);if i.direction<=0.0||i.magnitude<=EPSILON{return Err(StructuralCombineError::UnfavorableInteraction)}let work=experimental_combine_work_cost(a,b,e.candidate,water);if !work.is_finite(){return Err(StructuralCombineError::NonFiniteWorkCost)}let paid=work.max(e.threshold);if !paid.is_finite()||paid<0.0{return Err(StructuralCombineError::NonFiniteWorkCost)}Ok((i,work,paid))}
pub fn execute(s:&mut OrganismStructure,ua:usize,ub:usize,c:&[BaseResource],cache:&mut ConnectionCompatibilityCache,investment:f64,water:f64)->Result<StructuralCombineResult,StructuralCombineError>{if s.units.get(ua).is_none()||s.units.get(ub).is_none(){return Err(StructuralCombineError::MissingUnit)}if ua==ub||!investment.is_finite(){return if ua==ub{Err(StructuralCombineError::NoGeometricallyEligibleCandidate)}else{Err(StructuralCombineError::NonFiniteInvestment)}}let candidate=*connection_pair_candidates_cached(s,ua,ub,c,cache).iter().filter(|x|x.distance<=COMBINE_CONTACT_TOLERANCE&&x.available_a&&x.available_b).max_by(|a,b|a.facing.partial_cmp(&b.facing).unwrap_or(std::cmp::Ordering::Equal).then_with(||b.distance.partial_cmp(&a.distance).unwrap_or(std::cmp::Ordering::Equal))).ok_or(StructuralCombineError::NoGeometricallyEligibleCandidate)?;let a=s.units[ua].properties(c).ok_or(StructuralCombineError::MissingUnit)?;let b=s.units[ub].properties(c).ok_or(StructuralCombineError::MissingUnit)?;let formation=evaluate_formation(candidate,a.cohesion,b.cohesion);let(i,work,_)=required_investment(a,b,formation,water)?;if investment<formation.threshold.max(work){return Err(StructuralCombineError::InsufficientInvestment)}let surplus=investment-formation.threshold;let bs=bond_strength(a,b);if !bs.is_finite(){return Err(StructuralCombineError::NonFiniteBondStrength)}let be=surplus.max(0.0);let bi=crate::contact::try_add_bond(s,Bond{unit_a:ua,point_a:candidate.point_a,unit_b:ub,point_b:candidate.point_b,strength:bs,bond_energy:be},c).map_err(|_|StructuralCombineError::BondGeometryRejected)?;Ok(StructuralCombineResult{unit_a:ua,unit_b:ub,point_a:candidate.point_a,point_b:candidate.point_b,interaction:i,work_cost:work,formation_threshold:formation.threshold,investment,surplus,bond_strength:bs,bond_energy:be,bond_index:bi})}
pub fn instantiate_raw_unit(s:&mut OrganismStructure,raw:&mut Material,resource_name:&str,placement:Placement,c:&[BaseResource])->Result<usize,&'static str>{if c.iter().all(|r|r.name!=resource_name){return Err("resource type is not in the catalog")}if raw.parts.iter().all(|(n,a)|n!=resource_name||*a<1.0){return Err("insufficient raw material")}let mut remaining=Vec::with_capacity(raw.parts.len());for(n,a)in std::mem::take(&mut raw.parts){if n==resource_name{let next=a-1.0;if next>EPSILON{remaining.push((n,next))}}else{remaining.push((n,a))}}raw.parts=remaining;let material=Material::free_base(resource_name,1.0);let unit=StructuralUnit::from_material(material,placement).ok_or("invalid structural material")?;Ok(s.add_unit(unit))}
#[cfg(test)]mod tests{use super::*;use crate::resources::default_catalog;#[test]fn raw_stock_becomes_physical_unit_at_supplied_position(){let c=default_catalog();let mut raw=Material::free_base("Carbon",3.0);let mut s=OrganismStructure::new();let i=instantiate_raw_unit(&mut s,&mut raw,"Carbon",Placement{x:10.0,y:20.0,rotation_radians:0.5},&c).unwrap();assert_eq!(i,0);assert_eq!(s.units[0].placement.x,10.0);assert_eq!(raw.total_amount(),2.0)}#[test]fn failed_instantiation_does_not_consume_raw_material(){let c=default_catalog();let mut raw=Material::free_base("Carbon",0.5);let mut s=OrganismStructure::new();assert_eq!(instantiate_raw_unit(&mut s,&mut raw,"Carbon",Placement{x:0.0,y:0.0,rotation_radians:0.0},&c),Err("insufficient raw material"));assert_eq!(raw.total_amount(),0.5);assert!(s.units.is_empty())}#[test]fn failed_combine_does_not_mutate_structure(){let c=default_catalog();let mut s=OrganismStructure::new();let a=s.add_unit(StructuralUnit::new("Carbon",Placement{x:0.0,y:0.0,rotation_radians:0.0}));let mut cache=ConnectionCompatibilityCache::new();assert_eq!(execute(&mut s,a,a,&c,&mut cache,100.0,0.0),Err(StructuralCombineError::NoGeometricallyEligibleCandidate));assert!(s.bonds.is_empty())}}