use crate::decision::{ActionKind, OutcomeKind};
use crate::decision_runtime::ActionCandidate;
use crate::state::{ActiveTransformation, EnergyLedger, Environment, Organism, Simulation};
impl Simulation {
 pub(crate) fn try_start_transformation(organism:&mut Organism,catalog:&[crate::resources::BaseResource],next_id:&mut u64,decision:&ActionCandidate)->Option<ActiveTransformation>{if decision.action!=ActionKind::Break||organism.active_transformation_id.is_some(){return None}let key=decision.context_key.as_deref()?;let index=key.strip_prefix("bond:")?.parse::<usize>().ok()?;let bond=*organism.structure.bonds.get(index)?;if !bond.bond_energy.is_finite()||bond.bond_energy<0.0{return None}let a=organism.structure.units.get(bond.unit_a)?.properties(catalog)?;let b=organism.structure.units.get(bond.unit_b)?.properties(catalog)?;let complexity=crate::math::complexity(2.0);let _work=break_work_cost(a,b,complexity);let duration=1_u64.max(complexity.ceil() as u64);let t=ActiveTransformation{id:*next_id,organism_id:organism.id.clone(),kind:crate::state::TransformationKind::Break,material:crate::resources::Material::free_base("",0.0),bond:Some(bond),complexity,duration_ticks:duration,remaining_ticks:duration,decision_context_key:decision.context_key.clone()};*next_id+=1;organism.active_transformation_id=Some(t.id);Some(t)}
 pub(crate) fn resolve_transformation(transformation:&ActiveTransformation,organism:&mut Organism,environment:&mut Environment,ledger:&mut EnergyLedger){let Some(target)=transformation.bond else{organism.active_transformation_id=None;return};if target.unit_a>=organism.structure.units.len()||target.unit_b>=organism.structure.units.len(){organism.active_transformation_id=None;return}if !organism.structure.bonds.iter().any(|b|b.has_same_identity(&target)){organism.active_transformation_id=None;return}let a=match organism.structure.units[target.unit_a].properties(&environment.catalog){Some(x)=>x,None=>{organism.active_transformation_id=None;return}};let b=match organism.structure.units[target.unit_b].properties(&environment.catalog){Some(x)=>x,None=>{organism.active_transformation_id=None;return}};let work=break_work_cost(a,b,transformation.complexity);if organism.structure.break_matching_bond(target).is_none(){organism.active_transformation_id=None;return}organism.add_transaction_stress(work);if work.is_finite()&&work>0.0{ledger.total_heat_dissipated+=work;}let released=target.bond_energy.max(0.0);if released.is_finite()&&released>0.0{organism.usable_energy+=released;ledger.total_potential_energy_released+=released;ledger.total_usable_energy_gained+=released;}organism.active_transformation_id=None;let outcome=if released>0.0{OutcomeKind::Beneficial}else{OutcomeKind::Neutral};let candidate=ActionCandidate{action:ActionKind::Break,context_key:transformation.decision_context_key.clone()};crate::decision_runtime::record_outcome(&mut organism.decision_history,&candidate,outcome);if released>0.0{let reinforcement=(released*organism.genome.memory_strength()).clamp(0.0,1.0);let(x,y)=organism.occupied_cells.first().map(|p|(p.x,p.y)).unwrap_or((0.0,0.0));reinforce_memory_point(organism,x,y,reinforcement)}}
}
pub(crate) fn break_work_cost(a:crate::resources::ResourceProperties,b:crate::resources::ResourceProperties,complexity:f64)->f64{crate::combine::bond_strength(a,b)*complexity.max(0.0)}
pub(crate) fn reinforce_memory_point(organism:&mut Organism,x:f64,y:f64,reinforcement:f64){if let Some(point)=organism.memory.iter_mut().find(|p|(p.x-x).abs()<f64::EPSILON&&(p.y-y).abs()<f64::EPSILON){point.strength=crate::math::clamp01(point.strength+reinforcement)}else{organism.memory.push(crate::state::MemoryPoint{x,y,strength:crate::math::clamp01(reinforcement)})}}
