//! Physical contact and structural connection candidates.
use std::collections::HashMap;
use crate::connection_geometry::{facing_compatibility, point_distance, transform_connection_point};
use crate::organism_geometry::OrganismBodyGeometry;
use crate::resources::{ConnectionPoint, ConnectionSites};
use crate::state::Organism;
use crate::structure::{Bond, OrganismStructure, StructuralUnit};
fn transform_point(point:ConnectionPoint,unit:&StructuralUnit)->crate::connection_geometry::WorldConnectionPoint{transform_connection_point(point,unit.placement.x,unit.placement.y,unit.placement.rotation_radians)}
fn distance(a:crate::connection_geometry::WorldConnectionPoint,b:crate::connection_geometry::WorldConnectionPoint)->f64{point_distance(a,b)}
fn facing(a:crate::connection_geometry::WorldConnectionPoint,b:crate::connection_geometry::WorldConnectionPoint)->f64{facing_compatibility(a,b)}
pub fn world_connection_point(point:ConnectionPoint,unit:&StructuralUnit)->crate::connection_geometry::WorldConnectionPoint{transform_point(point,unit)}
pub fn connection_points_contact(a:ConnectionPoint,unit_a:&StructuralUnit,b:ConnectionPoint,unit_b:&StructuralUnit,tolerance:f64,_min_facing:f64)->bool{let wa=transform_point(a,unit_a);let wb=transform_point(b,unit_b);distance(wa,wb)<=tolerance.max(0.0)}
pub fn connection_point_distance(a:ConnectionPoint,unit_a:&StructuralUnit,b:ConnectionPoint,unit_b:&StructuralUnit)->f64{distance(transform_point(a,unit_a),transform_point(b,unit_b))}
#[derive(Clone,Copy,Debug,PartialEq)]pub struct ConnectionPairCandidate{pub point_a:usize,pub point_b:usize,pub distance:f64,pub facing:f64,pub load_a:f64,pub load_b:f64,pub available_a:bool,pub available_b:bool}
fn connection_point_has_space(s:&OrganismStructure,u:usize,p:usize)->bool{s.connection_count(u,p)==0}
pub fn connection_pair_candidates(s:&OrganismStructure,ua:usize,ub:usize,c:&[crate::resources::BaseResource])->Vec<ConnectionPairCandidate>{let Some(a)=s.units.get(ua)else{return Vec::new()};let Some(b)=s.units.get(ub)else{return Vec::new()};let Some(ConnectionSites::Corners(pa))=a.connection_sites(c)else{return Vec::new()};let Some(ConnectionSites::Corners(pb))=b.connection_sites(c)else{return Vec::new()};let mut out=Vec::new();for(ia,&x)in pa.iter().enumerate(){for(ib,&y)in pb.iter().enumerate(){let wa=transform_point(x,a);let wb=transform_point(y,b);out.push(ConnectionPairCandidate{point_a:ia,point_b:ib,distance:distance(wa,wb),facing:facing(wa,wb),load_a:s.connection_load(ua,ia,c),load_b:s.connection_load(ub,ib,c),available_a:connection_point_has_space(s,ua,ia),available_b:connection_point_has_space(s,ub,ib)});}}out}
pub fn contacting_connection_pair_candidates(s:&OrganismStructure,ua:usize,ub:usize,c:&[crate::resources::BaseResource],t:f64,m:f64)->Vec<ConnectionPairCandidate>{connection_pair_candidates(s,ua,ub,c).into_iter().filter(|x|x.distance<=t.max(0.0)&&x.facing>=m&&x.available_a&&x.available_b).collect()}
#[derive(Clone,Debug,PartialEq,Eq,Hash)]struct ConnectionTypeKey(String,String);impl ConnectionTypeKey{fn new(a:&str,b:&str)->Self{if a<=b{Self(a.into(),b.into())}else{Self(b.into(),a.into())}}}
#[derive(Clone,Debug,Default)]pub struct ConnectionCompatibilityCache{pairs:HashMap<ConnectionTypeKey,Vec<(usize,usize)>>}
impl ConnectionCompatibilityCache{pub fn new()->Self{Self::default()}pub fn pairs_for_owned(&mut self,a:&str,b:&str,c:&[crate::resources::BaseResource])->Vec<(usize,usize)>{let rev=a>b;let k=ConnectionTypeKey::new(a,b);if !self.pairs.contains_key(&k){self.pairs.insert(k.clone(),Self::build_pairs(&k.0,&k.1,c));}let p=self.pairs.get(&k).unwrap();if rev{p.iter().map(|(x,y)|(*y,*x)).collect()}else{p.clone()}}fn build_pairs(a:&str,b:&str,c:&[crate::resources::BaseResource])->Vec<(usize,usize)>{let Some(a)=c.iter().find(|r|r.name==a)else{return Vec::new()};let Some(b)=c.iter().find(|r|r.name==b)else{return Vec::new()};let ConnectionSites::Corners(pa)=a.shape.connection_sites()else{return Vec::new()};let ConnectionSites::Corners(pb)=b.shape.connection_sites()else{return Vec::new()};(0..pa.len()).flat_map(|i|(0..pb.len()).map(move|j|(i,j))).collect()}pub fn len(&self)->usize{self.pairs.len()}pub fn is_empty(&self)->bool{self.pairs.is_empty()}pub fn clear(&mut self){self.pairs.clear()}}
pub fn connection_pair_candidates_cached(s:&OrganismStructure,ua:usize,ub:usize,c:&[crate::resources::BaseResource],cache:&mut ConnectionCompatibilityCache)->Vec<ConnectionPairCandidate>{let Some(a)=s.units.get(ua)else{return Vec::new()};let Some(b)=s.units.get(ub)else{return Vec::new()};let(Some(ka),Some(kb))=(a.resource_name(),b.resource_name())else{return connection_pair_candidates(s,ua,ub,c)};let pairs=cache.pairs_for_owned(ka,kb,c);let Some(ConnectionSites::Corners(pa))=a.connection_sites(c)else{return Vec::new()};let Some(ConnectionSites::Corners(pb))=b.connection_sites(c)else{return Vec::new()};pairs.into_iter().filter_map(|(ia,ib)|{let wa=transform_point(*pa.get(ia)?,a);let wb=transform_point(*pb.get(ib)?,b);Some(ConnectionPairCandidate{point_a:ia,point_b:ib,distance:distance(wa,wb),facing:facing(wa,wb),load_a:s.connection_load(ua,ia,c),load_b:s.connection_load(ub,ib,c),available_a:connection_point_has_space(s,ua,ia),available_b:connection_point_has_space(s,ub,ib)})}).collect()}
pub fn try_add_bond(s:&mut OrganismStructure,b:Bond,c:&[crate::resources::BaseResource])->Result<usize,&'static str>{if !s.is_valid_bond(&b,c){return Err("invalid bond")}if !connection_point_has_space(s,b.unit_a,b.point_a)||!connection_point_has_space(s,b.unit_b,b.point_b){return Err("bond geometry overlaps existing bond")}Ok(s.add_bond(b))}
pub fn exposed_bonds_to_organism(attacker:&Organism,target:&Organism,catalog:&[crate::resources::BaseResource],_tolerance:f64)->Vec<Bond>{let Some(body)=OrganismBodyGeometry::from_structure(&attacker.structure,catalog)else{return Vec::new()};let mut exposed=Vec::new();for bond in &target.structure.bonds{let Some(unit_a)=target.structure.units.get(bond.unit_a)else{continue};let Some(unit_b)=target.structure.units.get(bond.unit_b)else{continue};let Some(ConnectionSites::Corners(points_a))=unit_a.connection_sites(catalog)else{continue};let Some(ConnectionSites::Corners(points_b))=unit_b.connection_sites(catalog)else{continue};let Some(point_a)=points_a.get(bond.point_a)else{continue};let Some(point_b)=points_b.get(bond.point_b)else{continue};let world_a=transform_point(*point_a,unit_a);let world_b=transform_point(*point_b,unit_b);if body.contains_point(world_a.x,world_a.y)||body.contains_point(world_b.x,world_b.y){exposed.push(*bond);}}exposed}

#[cfg(test)]mod tests{use super::*;use crate::resources::default_catalog;use crate::structure::{Placement,StructuralUnit};#[test]fn corner_contact_does_not_require_opposing_vertex_normals(){let catalog=default_catalog();let a=StructuralUnit::new("Carbon",Placement{x:0.0,y:0.0,rotation_radians:std::f64::consts::FRAC_PI_6});let r=0.438_691_f64;let b=StructuralUnit::new("Carbon",Placement{x:3.0_f64.sqrt()*r,y:0.0,rotation_radians:std::f64::consts::FRAC_PI_6});let pa=a.connection_sites(&catalog).unwrap();let pb=b.connection_sites(&catalog).unwrap();let(ConnectionSites::Corners(pa),ConnectionSites::Corners(pb))=(pa,pb)else{panic!("Carbon must expose corners")};assert!(connection_points_contact(pa[0],&a,pb[2],&b,1e-9,1.0-1e-9));}
#[test]fn cached_candidates_fall_back_for_composite_units(){let catalog=default_catalog();let m=crate::resources::Material{parts:vec![("Carbon".into(),1.0),("Hydrogen".into(),1.0)],internal_bonds:vec![crate::resources::InternalBond{part_a:0,part_b:1}]};let mut s=OrganismStructure::new();let a=s.add_unit(StructuralUnit::from_material(m.clone(),Placement{x:0.0,y:0.0,rotation_radians:0.0}).unwrap());let b=s.add_unit(StructuralUnit::from_material(m,Placement{x:1.0,y:0.0,rotation_radians:0.0}).unwrap());let mut cache=ConnectionCompatibilityCache::new();assert!(!connection_pair_candidates_cached(&s,a,b,&catalog,&mut cache).is_empty());}}