use crate::combine::experimental_interaction;
use crate::resources::Material;
use crate::state::{Environment,Organism,Position};
use crate::structure::OrganismStructure;
#[derive(Clone,Debug)]pub(crate)struct DecomposingBody{pub(crate)structure:OrganismStructure,pub(crate)energy_budget:f64,pub(crate)position:Position}
impl DecomposingBody{pub(crate)fn new(structure:OrganismStructure,energy_budget:f64,position:Position)->Option<Self>{if !energy_budget.is_finite()||energy_budget<0.0{return None}Some(Self{structure,energy_budget,position})}pub(crate)fn is_finished(&self)->bool{self.structure.bonds.is_empty()}}
pub(crate)struct DecompositionStep{pub(crate)net_energy:f64,pub(crate)bond_energy:f64,pub(crate)break_interaction_energy:f64,pub(crate)heat:f64,pub(crate)released_material:Option<Vec<Material>>}
fn water_field_amount(environment:&Environment,position:&Position)->f64{environment.field.index_for_position(position.x,position.y).map(|index|environment.field.cells[index].materials.iter().flat_map(|material|material.parts.iter()).filter(|(name,_)|name=="Water").map(|(_,amount)|*amount).sum()).unwrap_or(0.0)}
pub(crate)fn resolve_one_bond(body:&mut DecomposingBody,environment:&Environment)->Option<DecompositionStep>{let target=*body.structure.bonds.first()?;let ia=body.structure.unit_index(target.endpoint_a.constituent_id)?;let ib=body.structure.unit_index(target.endpoint_b.constituent_id)?;let a=body.structure.units.get(ia)?.properties(&environment.catalog)?;let b=body.structure.units.get(ib)?.properties(&environment.catalog)?;let candidate=crate::contact::connection_pair_candidates(&body.structure,ia,ib,&environment.catalog).into_iter().find(|candidate|candidate.endpoint_a==target.endpoint_a.location&&candidate.endpoint_b==target.endpoint_b.location)?;let interaction=experimental_interaction(a,b,candidate,water_field_amount(environment,&body.position));let break_interaction_energy=-interaction.signed_value;let complexity=crate::math::complexity(2.0);let work=crate::transformation::break_work_cost(a,b,complexity);if !work.is_finite()||work<0.0{return None}let net=target.bond_energy+break_interaction_energy-work;if !net.is_finite(){return None}if net<0.0{let deficit=-net;if body.energy_budget+f64::EPSILON<deficit{return None}body.energy_budget-=deficit}body.structure.break_matching_bond(target)?;let released_material=if body.is_finished(){Some(body.structure.units.iter().map(|unit|unit.material.clone()).collect())}else{None};Some(DecompositionStep{net_energy:net,bond_energy:target.bond_energy,break_interaction_energy,heat:work,released_material})}
pub(crate)fn harvestable_decomposition_energy(organisms:&[Organism],position:&Position)->Option<usize>{organisms.iter().enumerate().filter_map(|(index,organism)|{let organism_position=organism.occupied_cells.first()?;let distance=(organism_position.x-position.x).hypot(organism_position.y-position.y);Some((index,distance))}).min_by(|(_,a),(_,b)|a.partial_cmp(b).unwrap_or(std::cmp::Ordering::Equal)).map(|(index,_)|index)}
#[cfg(test)]mod tests{use super::*;use crate::genome::initial_genome;use crate::resources::default_catalog;#[test]fn retains_structure_budget_and_position(){let genome=initial_genome();let structure=genome.structural_blueprint.realize(&default_catalog()).unwrap();let body=DecomposingBody::new(structure,4.0,Position{x:2.0,y:3.0}).unwrap();assert!(!body.structure.units.is_empty());assert_eq!(body.energy_budget,4.0);assert_eq!(body.position,Position{x:2.0,y:3.0})}#[test]fn zero_bond_structure_is_finished(){let genome=initial_genome();let mut structure=genome.structural_blueprint.realize(&default_catalog()).unwrap();structure.bonds.clear();let body=DecomposingBody::new(structure,0.0,Position{x:0.0,y:0.0}).unwrap();assert!(body.is_finished())}}