#![expect(
    dead_code,
    reason = "Staged developmental-field API retained for solver integration"
)]

//! Continuous inherited developmental-field blueprint.
//!
//! This module stores developmental tendencies rather than an exact body plan.
//! It contains no constituent instances, coordinates, bonds, rotations,
//! silhouette, or guaranteed topology.

use crate::resources::{BaseResource, Material};
use crate::structural_blueprint::{
    BlueprintConnection, BlueprintElement, BlueprintPlacement, StructuralBlueprint,
};
use serde::{Deserialize, Serialize};

/// Current developmental realization floor for a juvenile derived from the adult blueprint.
pub const CANONICAL_JUVENILE_COUNT: usize = 12;

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
pub struct MaterialPreferenceField {
    pub resource_name: String,
    pub center_preference: f64,
    pub radial_falloff: f64,
}

impl MaterialPreferenceField {
    pub fn evaluate(&self, x: f64, y: f64) -> f64 {
        if !x.is_finite() || !y.is_finite() {
            return 0.0;
        }
        let radius_squared = x.mul_add(x, y * y);
        (self.center_preference * (-self.radial_falloff.max(0.0) * radius_squared).exp())
            .clamp(0.0, 1.0)
    }

    fn validate(&self) -> Result<(), String> {
        if self.resource_name.trim().is_empty()
            || !self.center_preference.is_finite()
            || !self.radial_falloff.is_finite()
            || self.radial_falloff < 0.0
        {
            return Err("material preference field is invalid".into());
        }
        Ok(())
    }
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
pub struct StructuralDensityField {
    pub center_preference: f64,
    pub radial_falloff: f64,
}

impl StructuralDensityField {
    pub fn evaluate(&self, x: f64, y: f64) -> f64 {
        if !x.is_finite() || !y.is_finite() {
            return 0.0;
        }
        let radius_squared = x.mul_add(x, y * y);
        (self.center_preference * (-self.radial_falloff.max(0.0) * radius_squared).exp())
            .clamp(0.0, 1.0)
    }

    fn validate(&self) -> Result<(), String> {
        if !self.center_preference.is_finite()
            || !self.radial_falloff.is_finite()
            || self.radial_falloff < 0.0
        {
            return Err("structural density field is invalid".into());
        }
        Ok(())
    }
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
pub struct ConnectivityField {
    pub strength: f64,
}

impl ConnectivityField {
    pub fn evaluate(&self, _x: f64, _y: f64) -> f64 {
        self.strength.clamp(0.0, 1.0)
    }

    fn validate(&self) -> Result<(), String> {
        if !self.strength.is_finite() || !(0.0..=1.0).contains(&self.strength) {
            return Err("connectivity field is invalid".into());
        }
        Ok(())
    }
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
pub struct DevelopmentalFieldBlueprint {
    pub material_preferences: Vec<MaterialPreferenceField>,
    pub structural_density: StructuralDensityField,
    pub connectivity: ConnectivityField,
}

impl DevelopmentalFieldBlueprint {
    /// Returns a transient physical construction candidate derived from the same
    /// developmental field at the requested realization scale.
    ///
    /// The field never stores exact structure. The discrete blueprint returned here
    /// is only a solver artifact and is validated through the physical realization
    /// machinery before it is accepted.
    pub fn construction_candidate(
        &self,
        catalog: &[BaseResource],
        preferred_mass: f64,
        juvenile: bool,
    ) -> Result<StructuralBlueprint, String> {
        self.validate()?;
        if catalog.is_empty() || !preferred_mass.is_finite() || preferred_mass <= 0.0 {
            return Err("developmental construction requires a finite positive preferred mass".into());
        }

        // Juveniles and adults use the same field. Juvenile construction begins
        // from the confirmed-good seed realization; development then evaluates
        // the same field at the reduced realization scale rather than selecting
        // a separate inherited body plan.
        let realization_fraction = if juvenile { 0.40 } else { 1.0 };
        let target_mass = preferred_mass * realization_fraction;
        let mut candidate = self.confirmed_seed_candidate(catalog)?;
        let mut current_mass = candidate.structural_mass(catalog);
        if !current_mass.is_finite() || current_mass <= 0.0 {
            return Err("confirmed developmental seed has invalid structural mass".into());
        }
        if current_mass + 1e-9 >= target_mass {
            return Ok(candidate);
        }

        // Search outward from the already-realized candidate. Positions and bonds
        // below are generated by the solver from physical geometry and field
        // preference; they are not inherited coordinates or topology.
        let mut attempts_without_progress = 0usize;
        while current_mass + 1e-9 < target_mass && attempts_without_progress < 64 {
            let Some((next, mass)) = self.best_growth_candidate(&candidate, catalog)? else {
                break;
            };
            if mass <= current_mass + 1e-9 {
                attempts_without_progress += 1;
                break;
            }
            candidate = next;
            current_mass = mass;
            attempts_without_progress = 0;
        }

        if current_mass + 1e-9 < target_mass && !juvenile {
            return Err("developmental field could not physically realize the preferred adult mass".into());
        }
        Ok(candidate)
    }

    fn confirmed_seed_candidate(&self, catalog: &[BaseResource]) -> Result<StructuralBlueprint, String> {
        // This is deliberately a known-good construction fixture, not a genome
        // count rule. It is the starting physical realization from which the
        // solver develops the same field toward the preferred adult mass.
        let resource = catalog
            .iter()
            .find(|r| matches!(r.shape.form, crate::resources::Form::Rectangle { .. }))
            .or_else(|| catalog.first())
            .ok_or_else(|| "catalog contains no constructible resource".to_string())?;
        let (width, height) = match resource.shape.form {
            crate::resources::Form::Rectangle { width, height } => (width, height),
            _ => (resource.shape.form.bounding_radius(), resource.shape.form.bounding_radius()),
        };
        let radius = (width + height).max(1e-6) * 0.5;
        let placements = [
            (0.0, radius, 0.0),
            (radius, 0.0, std::f64::consts::FRAC_PI_2),
            (0.0, -radius, 0.0),
            (-radius, 0.0, std::f64::consts::FRAC_PI_2),
        ];
        let mut elements = placements
            .into_iter()
            .map(|(x, y, rotation_radians)| BlueprintElement {
                material: Material::free_base(&resource.name, 1.0),
                placement: BlueprintPlacement { x, y, rotation_radians },
            })
            .collect::<Vec<_>>();
        let mut connections = (0..4)
            .map(|i| BlueprintConnection { element_a: i, element_b: (i + 1) % 4 })
            .collect::<Vec<_>>();
        let step = match resource.shape.form {
            crate::resources::Form::Rectangle { height, .. } => height,
            _ => resource.shape.form.bounding_radius().max(1e-6),
        };
        for i in 0..8 {
            let angle = (i as f64) * std::f64::consts::TAU / 8.0;
            let parent = i % 4;
            let parent_p = placements[parent];
            let placement = BlueprintPlacement {
                x: parent_p.0 + angle.cos() * step,
                y: parent_p.1 + angle.sin() * step,
                rotation_radians: angle,
            };
            let child = elements.len();
            elements.push(BlueprintElement {
                material: Material::free_base(&resource.name, 1.0),
                placement,
            });
            connections.push(BlueprintConnection { element_a: parent, element_b: child });
        }
        let candidate = StructuralBlueprint::with_anchor_elements(elements, connections, vec![0]);
        let structure = candidate.realize(catalog).map_err(|e| format!("seed realization failed: {e}"))?;
        let qualifies = crate::cavity::analyze_genome_cavity(&structure, catalog)
            .ok()
            .flatten()
            .is_some_and(|cavity| cavity.qualifies());
        if !qualifies {
            return Err("confirmed developmental seed does not satisfy the physical cavity contract".into());
        }
        Ok(candidate)
    }

    fn best_growth_candidate(
        &self,
        current: &StructuralBlueprint,
        catalog: &[BaseResource],
    ) -> Result<Option<(StructuralBlueprint, f64)>, String> {
        let mut best: Option<(f64, StructuralBlueprint, f64)> = None;
        let base_count = current.elements.len();
        let directions = 16usize;
        for parent in 0..base_count {
            let p = current.elements[parent].placement;
            for step in 0..directions {
                let angle = (step as f64) * std::f64::consts::TAU / directions as f64;
                let radius = catalog
                    .iter()
                    .find(|r| r.name == current.elements[parent].material.parts[0].0)
                    .map(|r| r.shape.form.bounding_radius().max(1e-6) * 1.5)
                    .unwrap_or(1.0);
                let placement = BlueprintPlacement {
                    x: p.x + angle.cos() * radius,
                    y: p.y + angle.sin() * radius,
                    rotation_radians: angle,
                };
                let mut candidate = current.clone();
                let resource = self.select_material(catalog, placement.x, placement.y)?;
                let child = candidate.elements.len();
                candidate.elements.push(BlueprintElement {
                    material: Material::free_base(&resource.name, 1.0),
                    placement,
                });
                candidate.connections.push(BlueprintConnection { element_a: parent, element_b: child });
                if !candidate.is_valid() {
                    continue;
                }
                let Ok(structure) = candidate.realize(catalog) else { continue; };
                let mass = structure.structural_mass(catalog);
                let field_score = self.material_preference(&resource.name, placement.x, placement.y)
                    + self.density_preference(placement.x, placement.y)
                    + self.connectivity_preference(placement.x, placement.y) * 0.25;
                let score = field_score + mass * 1e-6;
                if best.as_ref().is_none_or(|b| score > b.0) {
                    best = Some((score, candidate, mass));
                }
            }
        }
        Ok(best.map(|(_, candidate, mass)| (candidate, mass)))
    }

    fn select_material<'a>(&self, catalog: &'a [BaseResource], x: f64, y: f64) -> Result<&'a BaseResource, String> {
        catalog
            .iter()
            .max_by(|a, b| {
                self.material_preference(&a.name, x, y)
                    .partial_cmp(&self.material_preference(&b.name, x, y))
                    .unwrap_or(std::cmp::Ordering::Equal)
            })
            .ok_or_else(|| "catalog contains no material candidates".into())
    }

pub fn default_developmental_blueprint() -> DevelopmentalFieldBlueprint {
    DevelopmentalFieldBlueprint {
        material_preferences: vec![
            ("Carbon", 1.0),
            ("Nitrogen", 0.0),
            ("Phosphorus", 0.0),
            ("Sulfur", 0.0),
            ("Hydrogen", 0.0),
            ("Methane", 0.0),
            ("Water", 0.0),
        ]
        .into_iter()
        .map(
            |(resource_name, center_preference)| MaterialPreferenceField {
                resource_name: resource_name.into(),
                center_preference,
                radial_falloff: 0.0,
            },
        )
        .collect(),
        structural_density: StructuralDensityField {
            center_preference: 0.5,
            radial_falloff: 0.0,
        },
        connectivity: ConnectivityField { strength: 0.0 },
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn developmental_fields_are_continuous_evaluators() {
        let blueprint = default_developmental_blueprint();
        assert!(blueprint.validate().is_ok());
        assert!((blueprint.density_preference(0.0, 0.0) - 0.5).abs() < f64::EPSILON);
        assert!((blueprint.density_preference(2.0, 0.0) - 0.5).abs() < f64::EPSILON);
    }

    #[test]
    fn spatial_falloff_changes_preference_without_authored_coordinates() {
        let field = StructuralDensityField {
            center_preference: 1.0,
            radial_falloff: 0.5,
        };
        assert!(field.evaluate(0.0, 0.0) > field.evaluate(2.0, 0.0));
    }

    #[test]
    fn size_preference_maps_to_developmental_scale_without_mass_authority() {
        assert_eq!(
            DevelopmentalFieldBlueprint::preferred_developmental_scale(0.0),
            0.0
        );
        assert_eq!(
            DevelopmentalFieldBlueprint::preferred_developmental_scale(0.5),
            0.5
        );
        assert_eq!(
            DevelopmentalFieldBlueprint::preferred_developmental_scale(1.0),
            1.0
        );
    }

    #[test]
    fn construction_candidate_is_derived_from_fields_and_juvenile_scale() {
        let blueprint = default_developmental_blueprint();
        let catalog = crate::resources::default_catalog();
        let adult = blueprint
            .construction_candidate(&catalog, 0.5, false)
            .unwrap();
        let juvenile = blueprint
            .construction_candidate(&catalog, 0.5, true)
            .unwrap();
        assert!(adult.is_valid() && juvenile.is_valid());
        let adult_extent = adult
            .elements
            .iter()
            .map(|e| e.placement.x.abs().max(e.placement.y.abs()))
            .fold(0.0, f64::max);
        let juvenile_extent = juvenile
            .elements
            .iter()
            .map(|e| e.placement.x.abs().max(e.placement.y.abs()))
            .fold(0.0, f64::max);
        assert!(juvenile_extent < adult_extent);
    }

    #[test]
    fn connectivity_can_remain_inactive() {
        let blueprint = default_developmental_blueprint();
        assert_eq!(blueprint.connectivity_preference(0.0, 0.0), 0.0);
    }
}
