use rand::Rng;use rand_chacha::ChaCha8Rng;use serde::{Deserialize,Serialize};use std::collections::HashMap;use crate::attachment::{AttachmentFeature,BlueprintAttachment,BlueprintAttachmentTarget,BlueprintElementId,ConstituentAttachment,ConstituentId};use crate::material_structure::{InternalAttachmentBond,MaterialConstituent,MaterialStructure};use crate::resources::{default_catalog,Material};use crate::structural_blueprint::{BlueprintConnection,BlueprintElement,StructuralBlueprint};use crate::structural_material::StructuralMaterial;use crate::structure::Placement;
#[derive(Serialize,Deserialize,Clone,Debug)]pub struct TraitDef{pub name:String,pub value:f64,pub mutation_probability:f64,pub mutation_sigma:f64}
#[derive(Serialize,Deserialize,Clone,Debug)]pub struct Genome{pub traits:Vec<TraitDef>,#[serde(default="default_structural_blueprint")]pub structural_blueprint:StructuralBlueprint}
impl Genome{pub fn trait_value(&self,name:&str,default:f64)->f64{self.traits.iter().find(|t|t.name==name).map(|t|t.value).unwrap_or(default)}pub fn mass_affinity(&self)->f64{self.trait_value("mass_affinity",0.0).clamp(-1.0,1.0)}pub fn potential_energy_affinity(&self)->f64{self.trait_value("potential_energy_affinity",0.0).clamp(-1.0,1.0)}pub fn reactivity_affinity(&self)->f64{self.trait_value("reactivity_affinity",0.0).clamp(-1.0,1.0)}pub fn cohesion_affinity(&self)->f64{self.trait_value("cohesion_affinity",0.0).clamp(-1.0,1.0)}pub fn memory_strength(&self)->f64{self.trait_value("memory_strength",0.5).clamp(0.0,1.0)}pub fn perception_radius(&self)->f64{self.trait_value("perception_radius",100.0).max(0.0)}pub fn sensory_resolution(&self)->f64{self.trait_value("sensory_resolution",0.5).clamp(0.0,1.0)}pub fn directional_resolution(&self)->f64{self.trait_value("directional_resolution",1.0).clamp(0.0,1.0)}pub fn processing_efficiency(&self)->f64{self.trait_value("processing_efficiency",0.8).clamp(0.05,1.0)}pub fn movement_efficiency(&self)->f64{self.trait_value("movement_efficiency",0.8).clamp(0.05,1.0)}pub fn reproductive_investment(&self)->f64{self.trait_value("reproductive_investment",0.5).clamp(0.15,1.0)}pub fn mutate(&mut self,rng:&mut ChaCha8Rng){for t in &mut self.traits{if rng.gen::<f64>()<t.mutation_probability.clamp(1e-6,0.25){t.value+=rng.gen_range(-1.0..1.0)*t.mutation_sigma.max(0.0)}if rng.gen::<f64>()<0.001{t.mutation_probability=(t.mutation_probability*rng.gen_range(0.5..1.5)).clamp(1e-6,0.1)}}}}
fn trait_def(name:&str,value:f64,sigma:f64)->TraitDef{TraitDef{name:name.into(),value,mutation_probability:0.001,mutation_sigma:sigma}}
fn constituent(i:usize,r:&str)->MaterialConstituent{MaterialConstituent{id:ConstituentId((i+1)as u64),resource:r.into()}}
fn discrete_bond(a:usize,af:u32,b:usize,bf:u32)->InternalAttachmentBond{InternalAttachmentBond{a:ConstituentAttachment{constituent:ConstituentId((a+1)as u64),feature:AttachmentFeature::Discrete(af)},b:ConstituentAttachment{constituent:ConstituentId((b+1)as u64),feature:AttachmentFeature::Discrete(bf)}}}
fn composite(resources:&[&str],bonds:Vec<InternalAttachmentBond>)->Material{Material{composition:Vec::new(),structure:Some(MaterialStructure{constituents:resources.iter().enumerate().map(|(i,r)|constituent(i,r)).collect(),internal_bonds:bonds})}}
fn f_core_carbon_nitrogen()->Material{composite(&["Carbon","Carbon","Nitrogen"],vec![discrete_bond(0,0,1,3),discrete_bond(1,0,2,0)])}
fn hydrated_carbon_sulfur()->Material{composite(&["Carbon","Sulfur","Water"],vec![discrete_bond(0,0,1,0),InternalAttachmentBond{a:ConstituentAttachment{constituent:ConstituentId(2),feature:AttachmentFeature::Discrete(1)},b:ConstituentAttachment{constituent:ConstituentId(3),feature:AttachmentFeature::Fluid}}])}
fn hydrated_carbon_nitrogen_water()->Material{composite(&["Carbon","Nitrogen","Water"],vec![discrete_bond(0,0,1,0),InternalAttachmentBond{a:ConstituentAttachment{constituent:ConstituentId(2),feature:AttachmentFeature::Discrete(1)},b:ConstituentAttachment{constituent:ConstituentId(3),feature:AttachmentFeature::Fluid}}])}
fn constituent_attachment(material:&Material,element:BlueprintElementId,feature_index:u32)->BlueprintAttachment{let catalog=default_catalog();let structural=StructuralMaterial::from_material(material.clone()).expect("default blueprint material must be valid");let exposed=structural.exposed_discrete_attachments(&catalog).expect("default blueprint material must expose rigid attachment geometry");let(constituent,feature)=*exposed.get(feature_index as usize).expect("default blueprint attachment feature must exist");BlueprintAttachment{element,target:BlueprintAttachmentTarget::Constituent(constituent),feature:AttachmentFeature::Discrete(feature)}}
fn default_structural_blueprint()->StructuralBlueprint{let r=0.438_691_f64;let mut elements=Vec::with_capacity(61);let mut core_elements=Vec::with_capacity(19);let mut index_by_axial=HashMap::new();for ring in 0_i32..=4{for q in -4_i32..=4{for axial_r in -4_i32..=4{let current=q.abs().max(axial_r.abs()).max((q+axial_r).abs());if current!=ring{continue}let material=match ring{0..=2=>f_core_carbon_nitrogen(),3=>hydrated_carbon_sulfur(),4=>hydrated_carbon_nitrogen_water(),_=>unreachable!()};let x=3.0_f64.sqrt()*r*(q as f64+0.5*axial_r as f64);let y=1.5*r*axial_r as f64;let index=elements.len();let id=BlueprintElementId((index+1)as u64);if ring<=2{core_elements.push(id)}elements.push(BlueprintElement{id,material,placement:Placement{x,y,rotation_radians:std::f64::consts::FRAC_PI_6}});index_by_axial.insert((q,axial_r),index)}}}let mut connections=Vec::with_capacity(312);for q in -4_i32..=4{for axial_r in -4_i32..=4{let Some(&a)=index_by_axial.get(&(q,axial_r))else{continue};for(dq,dr,pa1,pb1,pa2,pb2)in[(1_i32,0_i32,0_u32,2_u32,5_u32,3_u32),(0_i32,1_i32,0_u32,4_u32,1_u32,3_u32),(-1_i32,1_i32,2_u32,4_u32,1_u32,5_u32)]{let Some(&b)=index_by_axial.get(&(q+dq,axial_r+dr))else{continue};let aid=elements[a].id;let bid=elements[b].id;connections.push(BlueprintConnection{a:constituent_attachment(&elements[a].material,aid,pa1),b:constituent_attachment(&elements[b].material,bid,pb1)});connections.push(BlueprintConnection{a:constituent_attachment(&elements[a].material,aid,pa2),b:constituent_attachment(&elements[b].material,bid,pb2)})}}}StructuralBlueprint::with_core_elements(elements,connections,core_elements)}
pub fn initial_genome()->Genome{Genome{traits:vec![trait_def("memory_strength",0.5,0.05),trait_def("perception_radius",100.0,1.0),trait_def("sensory_resolution",0.5,0.05),trait_def("directional_resolution",1.0,0.05),trait_def("mass_affinity",0.0,0.05),trait_def("potential_energy_affinity",0.5,0.05),trait_def("reactivity_affinity",0.0,0.05),trait_def("cohesion_affinity",0.0,0.05),trait_def("processing_efficiency",0.8,0.05),trait_def("movement_efficiency",0.8,0.05),trait_def("reproductive_investment",0.5,0.05)],structural_blueprint:default_structural_blueprint()}}