//! Exact two-dimensional interface geometry.
use crate::material_geometry::PlacedMaterialPart;
use crate::resources::Form;
const GEOMETRIC_EPSILON:f64=1e-12;
pub fn boundary_length(part:&PlacedMaterialPart)->f64{match &part.form{Form::Circle{radius} if radius.is_finite()&&*radius>0.0=>std::f64::consts::TAU*radius,Form::Line{length} if length.is_finite()&&*length>0.0=>*length,Form::Circle{..}|Form::Fluid{..}=>0.0,_=>world_polygon_vertices(part).map(|v|polygon_perimeter(&v)).unwrap_or(0.0)}}
pub fn shared_boundary_length(a:&PlacedMaterialPart,b:&PlacedMaterialPart,tolerance:f64)->f64{if !tolerance.is_finite()||tolerance<0.0{return 0.0}match(&a.form,&b.form){(Form::Circle{radius:ar},Form::Circle{radius:br})=>{if !ar.is_finite()||!br.is_finite()||*ar<=0.0||*br<=0.0{return 0.0}let coincident=(a.placement.x-b.placement.x).hypot(a.placement.y-b.placement.y)<=tolerance.max(GEOMETRIC_EPSILON);if coincident&&(ar-br).abs()<=tolerance.max(GEOMETRIC_EPSILON){std::f64::consts::TAU*ar}else{0.0}},(Form::Line{..},Form::Line{..})=>line_line_shared_length(a,b,tolerance),(Form::Line{..},polygon)=>line_polygon_shared_length(a,b,polygon,tolerance),(polygon,Form::Line{..})=>line_polygon_shared_length(b,a,polygon,tolerance),(Form::Fluid{..},_)|(_,Form::Fluid{..})=>0.0,(Form::Circle{..},_)|(_,Form::Circle{..})=>0.0,_=>polygon_shared_boundary_length(a,b,tolerance)}}
fn line_segment(part:&PlacedMaterialPart)->Option<((f64,f64),(f64,f64))>{let Form::Line{length}=part.form else{return None};let h=length/2.0;let(s,c)=part.placement.rotation_radians.sin_cos();Some(((part.placement.x-h*c,part.placement.y-h*s),(part.placement.x+h*c,part.placement.y+h*s)))}
fn line_line_shared_length(a:&PlacedMaterialPart,b:&PlacedMaterialPart,tolerance:f64)->f64{let(Some((a0,a1)),Some((b0,b1)))=(line_segment(a),line_segment(b))else{return 0.0};let ax=a1.0-a0.0;let ay=a1.1-a0.1;let length=ax.hypot(ay);if length<=GEOMETRIC_EPSILON{return 0.0}if cross(ax,ay,b0.0-a0.0,b0.1-a0.1).abs()>tolerance.max(GEOMETRIC_EPSILON)*length||cross(ax,ay,b1.0-a0.0,b1.1-a0.1).abs()>tolerance.max(GEOMETRIC_EPSILON)*length{return 0.0}let ux=ax/length;let uy=ay/length;let t0=(b0.0-a0.0)*ux+(b0.1-a0.1)*uy;let t1=(b1.0-a0.0)*ux+(b1.1-a0.1)*uy;(length.min(t0.max(t1))-0.0_f64.max(t0.min(t1))).max(0.0)}
fn line_polygon_shared_length(line:&PlacedMaterialPart,polygon:&PlacedMaterialPart,form:&Form,tolerance:f64)->f64{let Some((start,end))=line_segment(line)else{return 0.0};let Some(vertices)=world_polygon_vertices(polygon)else{return 0.0};let mut total=0.0;for(i,&edge_start)in vertices.iter().enumerate(){let edge_end=vertices[(i+1)%vertices.len()];total+=collinear_segment_overlap_length(start,end,edge_start,edge_end,tolerance)}total}
fn collinear_segment_overlap_length(a0:(f64,f64),a1:(f64,f64),b0:(f64,f64),b1:(f64,f64),tolerance:f64)->f64{let ax=a1.0-a0.0;let ay=a1.1-a0.1;let length=ax.hypot(ay);if length<=GEOMETRIC_EPSILON{return 0.0}let eps=tolerance.max(GEOMETRIC_EPSILON)*length;if cross(ax,ay,b0.0-a0.0,b0.1-a0.1).abs()>eps||cross(ax,ay,b1.0-a0.0,b1.1-a0.1).abs()>eps{return 0.0}let ux=ax/length;let uy=ay/length;let t0=(b0.0-a0.0)*ux+(b0.1-a0.1)*uy;let t1=(b1.0-a0.0)*ux+(b1.1-a0.1)*uy;(length.min(t0.max(t1))-0.0_f64.max(t0.min(t1))).max(0.0)}
fn cross(ax:f64,ay:f64,bx:f64,by:f64)->f64{ax*by-ay*bx}
fn world_polygon_vertices(part:&PlacedMaterialPart)->Option<Vec<(f64,f64)>>{let vertices=part.form.polygon_vertices()?;let(sin,cos)=part.placement.rotation_radians.sin_cos();Some(vertices.into_iter().map(|(x,y)|(part.placement.x+x*cos-y*sin,part.placement.y+x*sin+y*cos)).collect())}
fn polygon_perimeter(vertices:&[(f64,f64)])->f64{if vertices.len()<2{return 0.0}vertices.iter().enumerate().map(|(i,&(x1,y1))|{let(x2,y2)=vertices[(i+1)%vertices.len()];(x2-x1).hypot(y2-y1)}).sum()}
fn polygon_shared_boundary_length(a:&PlacedMaterialPart,b:&PlacedMaterialPart,tolerance:f64)->f64{let(Some(av),Some(bv))=(world_polygon_vertices(a),world_polygon_vertices(b))else{return 0.0};if polygons_interpenetrate(&av,&bv,tolerance){return 0.0}let mut total=0.0;for(i,&a0)in av.iter().enumerate(){let a1=av[(i+1)%av.len()];if segment_length(a0,a1)<=GEOMETRIC_EPSILON{continue}for(j,&b0)in bv.iter().enumerate(){let b1=bv[(j+1)%bv.len()];if segment_length(b0,b1)<=GEOMETRIC_EPSILON{continue}total+=collinear_segment_overlap_length(a0,a1,b0,b1,tolerance)}}total}
fn polygons_interpenetrate(a:&[(f64,f64)],b:&[(f64,f64)],tolerance:f64)->bool{polygons_have_transverse_boundary_crossing(a,b,tolerance)||polygon_has_strictly_interior_boundary_point(a,b,tolerance)||polygon_has_strictly_interior_boundary_point(b,a,tolerance)}
fn polygons_have_transverse_boundary_crossing(a:&[(f64,f64)],b:&[(f64,f64)],tolerance:f64)->bool{for(i,&a0)in a.iter().enumerate(){let a1=a[(i+1)%a.len()];if segment_length(a0,a1)<=GEOMETRIC_EPSILON{continue}for(j,&b0)in b.iter().enumerate(){let b1=b[(j+1)%b.len()];if segment_length(b0,b1)<=GEOMETRIC_EPSILON{continue}if segments_cross_transversely(a0,a1,b0,b1,tolerance){return true}}}false}
fn polygon_has_strictly_interior_boundary_point(subject:&[(f64,f64)],container:&[(f64,f64)],tolerance:f64)->bool{subject.iter().enumerate().any(|(i,&start)|{let end=subject[(i+1)%subject.len()];if segment_length(start,end)<=GEOMETRIC_EPSILON{return false}if point_is_strictly_inside_polygon(start,container,tolerance)||point_is_strictly_inside_polygon(end,container,tolerance){return true}let midpoint=((start.0+end.0)*0.5,(start.1+end.1)*0.5);point_is_strictly_inside_polygon(midpoint,container,tolerance)})}
fn point_is_strictly_inside_polygon(point:(f64,f64),polygon:&[(f64,f64)],tolerance:f64)->bool{if polygon.len()<3{return false}for(i,&start)in polygon.iter().enumerate(){let end=polygon[(i+1)%polygon.len()];if point_to_segment_distance(point,start,end)<=tolerance.max(GEOMETRIC_EPSILON){return false}}let mut inside=false;for(i,&(x1,y1))in polygon.iter().enumerate(){let(x2,y2)=polygon[(i+1)%polygon.len()];if(y1>point.1)!=(y2>point.1)&&point.0<x1+(point.1-y1)*(x2-x1)/(y2-y1){inside=!inside}}inside}
fn point_to_segment_distance(point:(f64,f64),start:(f64,f64),end:(f64,f64))->f64{let dx=end.0-start.0;let dy=end.1-start.1;let ls=dx*dx+dy*dy;if ls<=GEOMETRIC_EPSILON*GEOMETRIC_EPSILON{return(point.0-start.0).hypot(point.1-start.1)}let t=(((point.0-start.0)*dx+(point.1-start.1)*dy)/ls).clamp(0.0,1.0);let p=(start.0+t*dx,start.1+t*dy);(point.0-p.0).hypot(point.1-p.1)}
fn segments_cross_transversely(a0:(f64,f64),a1:(f64,f64),b0:(f64,f64),b1:(f64,f64),tolerance:f64)->bool{let ax=a1.0-a0.0;let ay=a1.1-a0.1;let bx=b1.0-b0.0;let by=b1.1-b0.1;let scale=ax.hypot(ay).max(1.0)*bx.hypot(by).max(1.0);let eps=tolerance.max(GEOMETRIC_EPSILON)*scale;if cross(ax,ay,bx,by).abs()<=eps{return false}let c1=cross(ax,ay,b0.0-a0.0,b0.1-a0.1);let c2=cross(ax,ay,b1.0-a0.0,b1.1-a0.1);let c3=cross(bx,by,a0.0-b0.0,a0.1-b0.1);let c4=cross(bx,by,a1.0-b0.0,a1.1-b0.1);((c1>eps&&c2<-eps)||(c1<-eps&&c2>eps))&&((c3>eps&&c4<-eps)||(c3<-eps&&c4>eps))}
fn segment_length(a:(f64,f64),b:(f64,f64))->f64{(b.0-a.0).hypot(b.1-a.1)}
#[cfg(test)]mod tests{use super::*;use crate::resources::Form;use crate::structure::Placement;fn part(form:Form,x:f64,y:f64,rotation_radians:f64)->PlacedMaterialPart{PlacedMaterialPart{part_index:0,form,placement:Placement{x,y,rotation_radians}}}
#[test]fn circle_boundary_length_is_exact_circumference(){let c=part(Form::Circle{radius:2.0},0.0,0.0,0.0);assert!((boundary_length(&c)-4.0*std::f64::consts::PI).abs()<1e-12)}
#[test]fn line_boundary_length_is_exact_length(){let l=part(Form::Line{length:3.0},0.0,0.0,0.0);assert_eq!(boundary_length(&l),3.0)}
#[test]fn rectangle_boundary_length_is_exact_perimeter(){let r=part(Form::Rectangle{width:4.0,height:2.0},0.0,0.0,0.0);assert!((boundary_length(&r)-12.0).abs()<1e-12)}
#[test]fn tangent_circles_have_zero_shared_boundary_length(){let a=part(Form::Circle{radius:1.0},0.0,0.0,0.0);let b=part(Form::Circle{radius:1.0},2.0,0.0,0.0);assert_eq!(shared_boundary_length(&a,&b,0.0),0.0)}
#[test]fn coincident_circles_share_their_entire_circumference(){let a=part(Form::Circle{radius:2.0},5.0,-3.0,0.0);let b=part(Form::Circle{radius:2.0},5.0,-3.0,0.0);assert!((shared_boundary_length(&a,&b,0.0)-4.0*std::f64::consts::PI).abs()<1e-12)}
#[test]fn line_segments_share_collinear_overlap(){let a=part(Form::Line{length:4.0},0.0,0.0,0.0);let b=part(Form::Line{length:2.0},1.0,0.0,0.0);assert!((shared_boundary_length(&a,&b,0.0)-1.0).abs()<1e-12)}
#[test]fn crossing_polygons_have_zero_shared_boundary_length(){let a=part(Form::Rectangle{width:4.0,height:1.0},0.0,0.0,0.0);let b=part(Form::Rectangle{width:1.0,height:4.0},0.0,0.0,0.0);assert_eq!(shared_boundary_length(&a,&b,0.0),0.0)}
#[test]fn contained_polygon_has_no_shared_boundary_length(){let a=part(Form::Rectangle{width:6.0,height:4.0},0.0,0.0,0.0);let b=part(Form::Rectangle{width:2.0,height:1.0},0.0,0.0,0.0);assert_eq!(shared_boundary_length(&a,&b,0.0),0.0)}
#[test]fn identical_rectangles_share_the_full_perimeter(){let a=part(Form::Rectangle{width:4.0,height:2.0},0.0,0.0,0.0);let b=part(Form::Rectangle{width:4.0,height:2.0},0.0,0.0,0.0);assert!((shared_boundary_length(&a,&b,0.0)-12.0).abs()<1e-12)}
#[test]fn partially_shared_collinear_edges_return_exact_overlap(){let a=part(Form::Rectangle{width:4.0,height:2.0},0.0,0.0,0.0);let b=part(Form::Rectangle{width:2.0,height:2.0},3.0,0.0,0.0);assert!((shared_boundary_length(&a,&b,0.0)-2.0).abs()<1e-12)}
#[test]fn rotated_identical_polygons_share_the_same_boundary_when_rotation_matches(){let angle=std::f64::consts::FRAC_PI_4;let a=part(Form::Rectangle{width:4.0,height:2.0},10.0,20.0,angle);let b=part(Form::Rectangle{width:4.0,height:2.0},10.0,20.0,angle);assert!((shared_boundary_length(&a,&b,0.0)-12.0).abs()<1e-10)}
#[test]fn fluid_has_no_boundary_length_without_authoritative_geometry(){let f=part(Form::Fluid{nominal_area:100.0},0.0,0.0,0.0);assert_eq!(boundary_length(&f),0.0);assert_eq!(shared_boundary_length(&f,&f,0.0),0.0)}}
