//! Browser-facing observation contracts derived from simulation truth.
use serde::{Deserialize, Serialize};
use crate::organism_geometry::OrganismBodyGeometry;
use crate::state::Simulation;
use crate::structure::ConnectionEndpoint;
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)] pub(crate) enum ObservationLevel { World, Organism, Structure }
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)] pub(crate) struct ObservationContext { pub(crate) level: ObservationLevel, #[serde(default)] pub(crate) organism_ids: Vec<String>, #[serde(default)] pub(crate) focused_organism_id: Option<String> }
impl ObservationContext { pub(crate) fn world()->Self{Self{level:ObservationLevel::World,organism_ids:Vec::new(),focused_organism_id:None}} pub(crate) fn organism(organism_ids:Vec<String>)->Self{Self{level:ObservationLevel::Organism,organism_ids,focused_organism_id:None}} pub(crate) fn structure(organism_ids:Vec<String>,focused_organism_id:Option<String>)->Self{Self{level:ObservationLevel::Structure,organism_ids,focused_organism_id}} }
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)] pub(crate) struct ObservationProjection { pub(crate) context:ObservationContext,pub(crate) payload:ObservationPayload }
impl ObservationProjection { pub(crate) fn world(payload:WorldObservation)->Self{Self{context:ObservationContext::world(),payload:ObservationPayload::World(payload)}} pub(crate) fn organism(context:ObservationContext,payload:OrganismObservation)->Option<Self>{if context.level!=ObservationLevel::Organism{return None}Some(Self{context,payload:ObservationPayload::Organism(payload)})} pub(crate) fn structure(context:ObservationContext,payload:StructureObservation)->Option<Self>{if context.level!=ObservationLevel::Structure{return None}Some(Self{context,payload:ObservationPayload::Structure(payload)})} }
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)] pub(crate) struct WorldOrganismObservation { pub(crate) id:String,pub(crate) x:f64,pub(crate) y:f64,pub(crate) min_x:f64,pub(crate) max_x:f64,pub(crate) min_y:f64,pub(crate) max_y:f64,pub(crate) silhouette:Vec<OrganismSilhouettePart> }
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)] pub(crate) struct WorldFieldObservation { pub(crate) cell_index:usize,pub(crate) x:f64,pub(crate) y:f64,pub(crate) materials:Vec<(String,f64)> }
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)] pub(crate) struct WorldPointObservation { pub(crate) x:f64,pub(crate) y:f64 }
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)] pub(crate) struct WorldObservation { pub(crate) width:f64,pub(crate) height:f64,pub(crate) organisms:Vec<WorldOrganismObservation>,pub(crate) field:Vec<WorldFieldObservation>,pub(crate) vents:Vec<WorldPointObservation>,pub(crate) decomposing_bodies:Vec<WorldPointObservation> }
impl WorldObservation { pub(crate) fn from_simulation(simulation:&Simulation)->Self { let catalog=&simulation.environment.catalog; let organisms=simulation.organisms.iter().map(|organism|{let position=organism.occupied_cells.first().map(|p|(p.x,p.y)).unwrap_or((0.0,0.0));let(min_x,max_x,min_y,max_y,silhouette)=match OrganismBodyGeometry::from_structure(&organism.structure,catalog){Some(geometry)=>{let silhouette=geometry.parts.into_iter().map(|part|OrganismSilhouettePart{form:part.form,x:part.x+position.0,y:part.y+position.1,rotation_radians:part.rotation_radians}).collect();(geometry.min_x+position.0,geometry.max_x+position.0,geometry.min_y+position.1,geometry.max_y+position.1,silhouette)},None=>(position.0,position.0,position.1,position.1,Vec::new())};WorldOrganismObservation{id:organism.id.clone(),x:position.0,y:position.1,min_x,max_x,min_y,max_y,silhouette}}).collect();let field=simulation.environment.field.cells.iter().enumerate().filter_map(|(cell_index,cell)|{let materials=cell.total_material();if materials.is_empty(){return None}let(x,y)=simulation.environment.field.cell_center(cell_index);Some(WorldFieldObservation{cell_index,x,y,materials})}).collect();let vents=simulation.environment.vents.iter().map(|v|WorldPointObservation{x:v.x,y:v.y}).collect();let decomposing_bodies=simulation.decomposing_bodies.iter().map(|b|WorldPointObservation{x:b.position.x,y:b.position.y}).collect();Self{width:simulation.environment.width,height:simulation.environment.height,organisms,field,vents,decomposing_bodies}} }
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)] pub(crate) struct OrganismObservation { pub(crate) id:String,pub(crate) x:f64,pub(crate) y:f64,pub(crate) min_x:f64,pub(crate) max_x:f64,pub(crate) min_y:f64,pub(crate) max_y:f64,pub(crate) silhouette:Vec<OrganismSilhouettePart>,pub(crate) unit_count:usize,pub(crate) bond_count:usize }
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)] pub(crate) struct OrganismSilhouettePart { pub(crate) form:crate::resources::Form,pub(crate) x:f64,pub(crate) y:f64,pub(crate) rotation_radians:f64 }
impl OrganismObservation { pub(crate) fn from_simulation(simulation:&Simulation,organism_id:&str)->Option<Self>{let organism=simulation.organisms.iter().find(|o|o.id==organism_id)?;let position=organism.occupied_cells.first()?;let geometry=OrganismBodyGeometry::from_structure(&organism.structure,&simulation.environment.catalog)?;let silhouette=geometry.parts.into_iter().map(|part|OrganismSilhouettePart{form:part.form,x:part.x+position.x,y:part.y+position.y,rotation_radians:part.rotation_radians}).collect();Some(Self{id:organism.id.clone(),x:position.x,y:position.y,min_x:geometry.min_x+position.x,max_x:geometry.max_x+position.x,min_y:geometry.min_y+position.y,max_y:geometry.max_y+position.y,silhouette,unit_count:organism.structure.units.len(),bond_count:organism.structure.bonds.len()})} }
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)] pub(crate) struct StructureObservation { pub(crate) id:String,pub(crate) units:Vec<StructureUnitObservation>,pub(crate) bonds:Vec<StructureBondObservation> }
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)] pub(crate) struct StructureUnitObservation { pub(crate) unit_index:usize,pub(crate) material:crate::resources::Material,pub(crate) placement:crate::structure::Placement,pub(crate) form:Option<crate::resources::Form> }
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)] pub(crate) struct StructureBondObservation { pub(crate) unit_a:usize,pub(crate) point_a:ConnectionEndpoint,pub(crate) unit_b:usize,pub(crate) point_b:ConnectionEndpoint,pub(crate) strength:f64,pub(crate) bond_energy:f64,pub(crate) endpoint_a:Option<WorldPointObservation>,pub(crate) endpoint_b:Option<WorldPointObservation> }
impl StructureObservation { pub(crate) fn from_simulation(simulation:&Simulation,organism_id:&str)->Option<Self>{let organism=simulation.organisms.iter().find(|o|o.id==organism_id)?;let catalog=&simulation.environment.catalog;let units=organism.structure.units.iter().enumerate().map(|(unit_index,unit)|StructureUnitObservation{unit_index,material:unit.material.material().clone(),placement:unit.placement,form:unit.shape(catalog).map(|s|s.form.clone())}).collect();let bonds=organism.structure.bonds.iter().map(|bond|StructureBondObservation{unit_a:bond.unit_a,point_a:bond.point_a,unit_b:bond.unit_b,point_b:bond.point_b,strength:bond.strength,bond_energy:bond.bond_energy,endpoint_a:connection_endpoint(&organism.structure,bond.unit_a,bond.point_a,catalog),endpoint_b:connection_endpoint(&organism.structure,bond.unit_b,bond.point_b,catalog)}).collect();Some(Self{id:organism.id.clone(),units,bonds})} }
fn connection_endpoint(structure:&crate::structure::OrganismStructure,unit_index:usize,endpoint:ConnectionEndpoint,catalog:&[crate::resources::BaseResource])->Option<WorldPointObservation>{let unit=structure.units.get(unit_index)?;let local=structure.connection_endpoint_local(unit_index,endpoint,catalog)?;let rotation=unit.placement.rotation_radians;let(sin,cos)=rotation.sin_cos();Some(WorldPointObservation{x:unit.placement.x+local.x*cos-local.y*sin,y:unit.placement.y+local.x*sin+local.y*cos})}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)] pub(crate) enum ObservationPayload{World(WorldObservation),Organism(OrganismObservation),Structure(StructureObservation)}
#[cfg(test)] mod tests {use super::*;#[test]fn observation_levels_are_semantic_not_zoom_values(){assert_ne!(ObservationLevel::World,ObservationLevel::Organism);assert_ne!(ObservationLevel::Organism,ObservationLevel::Structure)}#[test]fn world_context_contains_no_selection(){let c=ObservationContext::world();assert_eq!(c.level,ObservationLevel::World);assert!(c.organism_ids.is_empty());assert!(c.focused_organism_id.is_none())}#[test]fn structure_context_preserves_stable_ids_and_focus(){let c=ObservationContext::structure(vec!["17".into(),"23".into()],Some("23".into()));assert_eq!(c.level,ObservationLevel::Structure);assert_eq!(c.organism_ids,vec!["17","23"]);assert_eq!(c.focused_organism_id.as_deref(),Some("23"))}#[test]fn projection_rejects_payload_at_wrong_level(){let c=ObservationContext::world();let s=Simulation::new(1,20.0);let p=OrganismObservation::from_simulation(&s,"1").unwrap();assert!(ObservationProjection::organism(c,p).is_none())}#[test]fn world_observation_preserves_authoritative_organism_ids(){let s=Simulation::new(1,20.0);let o=WorldObservation::from_simulation(&s);assert_eq!(o.organisms.len(),1);assert_eq!(o.organisms[0].id,"1")}#[test]fn world_observation_exposes_authoritative_silhouette(){let s=Simulation::new(1,20.0);let o=WorldObservation::from_simulation(&s);let x=&o.organisms[0];assert!(x.max_x>=x.min_x);assert!(x.max_y>=x.min_y);assert!(!x.silhouette.is_empty())}#[test]fn organism_observation_preserves_identity_and_structure_counts(){let s=Simulation::new(1,20.0);let o=OrganismObservation::from_simulation(&s,"1").unwrap();assert_eq!(o.id,"1");assert!(o.unit_count>0);assert!(o.bond_count>0);assert!(!o.silhouette.is_empty())}#[test]fn structure_observation_preserves_material_placement_and_bonds(){let s=Simulation::new(1,20.0);let o=StructureObservation::from_simulation(&s,"1").unwrap();assert_eq!(o.id,"1");assert!(!o.units.is_empty());assert!(!o.bonds.is_empty());assert!(o.units.iter().all(|u|u.form.is_some()));assert!(o.bonds.iter().all(|b|b.endpoint_a.is_some()&&b.endpoint_b.is_some()))}#[test]fn observation_projection_round_trips_through_json(){let s=Simulation::new(1,20.0);let p=ObservationProjection::structure(ObservationContext::structure(vec!["1".into()],Some("1".into())),StructureObservation::from_simulation(&s,"1").unwrap()).unwrap();let encoded=serde_json::to_string(&p).unwrap();let decoded:ObservationProjection=serde_json::from_str(&encoded).unwrap();assert_eq!(serde_json::from_str::<serde_json::Value>(&encoded).unwrap(),serde_json::to_value(&decoded).unwrap())}}
