//! Physical reproduction lifecycle.
use rand_chacha::ChaCha8Rng;
use std::collections::{HashMap,HashSet};
use crate::attachment::{BlueprintElementId,ConstituentAttachment,ConstituentId};
use crate::material_storage::MaterialStorage;
use crate::resources::{BaseResource,Material};
use crate::state::{DevelopmentStage,Organism,ReproductiveConstruction,ResourceSense};
use crate::structure::{OrganismStructure,StructuralUnit};
const JUVENILE_MATURE_MASS_FRACTION:f64=0.40;
fn assemble_blueprint_material(remaining:&mut MaterialStorage,target:&Material)->Option<Material>{
 if let Some(s)=target.structure(){let mut constituents=Vec::with_capacity(s.constituents.len());for c in &s.constituents{remaining.take_one_unstructured_named(&c.resource)?;constituents.push(crate::material_structure::MaterialConstituent{id:ConstituentId((constituents.len()+1)as u64),resource:c.resource.clone()});}
  let mut bonds=Vec::with_capacity(s.internal_bonds.len());for b in &s.internal_bonds{let remap=|a:&ConstituentAttachment|ConstituentAttachment{constituent:ConstituentId(s.constituents.iter().position(|c|c.id==a.constituent)? as u64+1),feature:a.feature};bonds.push(crate::material_structure::InternalAttachmentBond{a:remap(&b.a),b:remap(&b.b)});}return Some(Material{composition:Vec::new(),structure:Some(crate::material_structure::MaterialStructure{constituents,internal_bonds:bonds})})}
 let[c]=target.composition()else{return None};if(c.amount-1.0).abs()>f64::EPSILON{return None}remaining.take_one_unstructured_named(&c.resource)
}
fn frontier(blueprint:&crate::structural_blueprint::StructuralBlueprint,realized:&HashMap<BlueprintElementId,usize>,allowed:&HashSet<BlueprintElementId>)->Vec<BlueprintElementId>{allowed.iter().copied().filter(|id|!realized.contains_key(id)&&blueprint.connections.iter().any(|c|(c.a.element==*id&&realized.contains_key(&c.b.element))||(c.b.element==*id&&realized.contains_key(&c.a.element)))).collect()}
fn realized_mapping(realized_elements:&[BlueprintElementId])->HashMap<BlueprintElementId,usize>{realized_elements.iter().enumerate().map(|(structure_index,id)|(*id,structure_index)).collect()}
fn element_by_id<'a>(blueprint:&'a crate::structural_blueprint::StructuralBlueprint,id:BlueprintElementId)->Option<&'a crate::structural_blueprint::BlueprintElement>{blueprint.elements.iter().find(|e|e.id==id)}
fn juvenile_target_set(blueprint:&crate::structural_blueprint::StructuralBlueprint,catalog:&[BaseResource])->Option<HashSet<BlueprintElementId>>{if !blueprint.is_valid(){return None}let core=blueprint.core_elements.iter().copied().collect::<HashSet<_>>();let target_mass=blueprint.structural_mass(catalog)*JUVENILE_MATURE_MASS_FRACTION;let mut selected=core.clone();let mut current_mass=selected.iter().filter_map(|id|element_by_id(blueprint,*id)).map(|e|e.material.mass(catalog)).sum::<f64>();while current_mass+f64::EPSILON<target_mass{let realized=selected.iter().copied().map(|id|(id,usize::MAX)).collect::<HashMap<_,_>>();let next=frontier(blueprint,&realized,&all_ids(blueprint)).into_iter().min_by_key(|id|id.0)?;selected.insert(next);current_mass+=element_by_id(blueprint,next)?.material.mass(catalog);}Some(selected)}
fn all_ids(blueprint:&crate::structural_blueprint::StructuralBlueprint)->HashSet<BlueprintElementId>{blueprint.elements.iter().map(|e|e.id).collect()}
fn add_blueprint_element(structure:&mut OrganismStructure,realized:&HashMap<BlueprintElementId,usize>,blueprint_id:BlueprintElementId,material:Material,blueprint:&crate::structural_blueprint::StructuralBlueprint,catalog:&[BaseResource])->Option<(usize,f64)>{let element=element_by_id(blueprint,blueprint_id)?;let unit=StructuralUnit::from_material(material,element.placement)?;let mut candidate=structure.clone();let new_index=candidate.add_unit(unit);let mut stress=0.0;for connection in &blueprint.connections{let other=if connection.a.element==blueprint_id{Some(connection.b.element)}else if connection.b.element==blueprint_id{Some(connection.a.element)}else{None};let Some(other_blueprint)=other else{continue};if !realized.contains_key(&other_blueprint){continue}let mapped=if connection.a.element==blueprint_id{*connection}else{crate::structural_blueprint::BlueprintConnection{a:connection.b,b:connection.a}};stress+=crate::structural_blueprint::realize_connection(&mut candidate,mapped,catalog).ok()?;}*structure=candidate;Some((new_index,stress))}
fn construct_any_frontier_element(stored:&MaterialStorage,structure:&mut OrganismStructure,realized:&HashMap<BlueprintElementId,usize>,allowed:&HashSet<BlueprintElementId>,blueprint:&crate::structural_blueprint::StructuralBlueprint,catalog:&[BaseResource])->Option<(BlueprintElementId,MaterialStorage,f64,usize)>{let mut candidates=frontier(blueprint,realized,allowed);candidates.sort_unstable_by_key(|id|id.0);for id in candidates{let mut remaining=stored.clone();let Some(element)=element_by_id(blueprint,id)else{continue};let Some(material)=assemble_blueprint_material(&mut remaining,&element.material)else{continue};let mut candidate_structure=structure.clone();let Some((si,stress))=add_blueprint_element(&mut candidate_structure,realized,id,material,blueprint,catalog)else{continue};*structure=candidate_structure;return Some((id,remaining,stress,si));}None}
pub(crate)fn begin_reproduction(parent:&mut Organism,rng:&mut ChaCha8Rng,catalog:&[BaseResource])->bool{if !matches!(parent.development_stage,DevelopmentStage::Adult)||parent.reproductive_readiness<1.0-f64::EPSILON||parent.reproductive_construction.is_some(){return false}let mut child_genome=parent.genome.clone();child_genome.mutate(rng);let blueprint=&child_genome.structural_blueprint;let Some(target_set)=juvenile_target_set(blueprint,catalog)else{return false};let core=blueprint.core_elements.iter().copied().collect::<HashSet<_>>();let mut remaining=parent.stored_material.clone();let mut structure=OrganismStructure::new();let mut realized=HashMap::new();let mut realized_elements=Vec::new();let mut initial_stress=0.0;while realized.len()<core.len(){let Some((id,next_remaining,stress,si))=construct_any_frontier_element(&remaining,&mut structure,&realized,&core,blueprint,catalog).or_else(||{for id in &core{let mut trial_remaining=remaining.clone();let Some(element)=element_by_id(blueprint,*id)else{continue};let Some(material)=assemble_blueprint_material(&mut trial_remaining,&element.material)else{continue};let mut trial_structure=structure.clone();let empty=HashMap::new();let Some((new_index,stress))=add_blueprint_element(&mut trial_structure,&empty,*id,material,blueprint,catalog)else{continue};structure=trial_structure;return Some((*id,trial_remaining,stress,new_index));}None})else{return false};remaining=next_remaining;realized.insert(id,si);realized_elements.push(id);initial_stress+=stress;}parent.stored_material=remaining;parent.reproductive_readiness=0.0;parent.add_transaction_stress(initial_stress);parent.reproductive_construction=Some(ReproductiveConstruction{committed_material:MaterialStorage::default(),developing_structure:structure,child_genome,target_elements:target_set.into_iter().collect(),realized_elements,pending_stress:0.0});true}
pub(crate)fn advance_construction(stored:&mut MaterialStorage,construction:&mut ReproductiveConstruction,catalog:&[BaseResource])->Option<f64>{let blueprint=&construction.child_genome.structural_blueprint;let target=construction.target_elements.iter().copied().collect::<HashSet<_>>();let realized=realized_mapping(&construction.realized_elements);if realized.len()>=target.len(){return None}let(id,remaining,stress,si)=construct_any_frontier_element(stored,&mut construction.developing_structure,&realized,&target,blueprint,catalog)?;*stored=remaining;construction.realized_elements.push(id);debug_assert_eq!(si,construction.developing_structure.units.len()-1);Some(stress)}
pub(crate)fn finish_reproduction(parent:&mut Organism,child_id:String)->Option<Organism>{let construction=parent.reproductive_construction.take()?;let target=construction.target_elements.iter().copied().collect::<HashSet<_>>();let realized=construction.realized_elements.iter().copied().collect::<HashSet<_>>();if realized!=target||!construction.committed_material.is_empty(){parent.reproductive_construction=Some(construction);return None}let position=parent.occupied_cells.first().cloned()?;Some(Organism{id:child_id,occupied_cells:vec![position],genome:construction.child_genome,resource_sense:ResourceSense{sensed_resources:Vec::new(),direction_x:0.0,direction_y:0.0,direction_strength:0.0},memory:Vec::new(),decision_history:crate::decision::DecisionHistory::default(),usable_energy:0.0,stress:0.0,stress_threshold:crate::state::INITIAL_STRESS_THRESHOLD,stored_material:MaterialStorage::default(),development_stage:DevelopmentStage::Juvenile,age:0,reproductive_readiness:0.0,active_transformation_id:None,reproductive_construction:None,structure:construction.developing_structure})}
#[cfg(test)]mod tests{use super::*;use crate::genome::initial_genome;use crate::resources::default_catalog;#[test]fn reproduction_uses_blueprint_genome_core(){let g=initial_genome();assert_eq!(g.structural_blueprint.core_elements.len(),19);assert!(g.structural_blueprint.validate().is_ok())}#[test]fn reproduction_target_contains_entire_core(){let g=initial_genome();let t=juvenile_target_set(&g.structural_blueprint,&default_catalog()).unwrap();assert!(g.structural_blueprint.core_elements.iter().all(|i|t.contains(i)))}#[test]fn reproduction_target_is_at_least_forty_percent(){let g=initial_genome();let c=default_catalog();let t=juvenile_target_set(&g.structural_blueprint,&c).unwrap();let mature=g.structural_blueprint.structural_mass(&c);let mass=t.iter().filter_map(|id|element_by_id(&g.structural_blueprint,*id)).map(|e|e.material.mass(&c)).sum::<f64>();assert!(mass+f64::EPSILON>=mature*JUVENILE_MATURE_MASS_FRACTION)}#[test]fn realized_mapping_preserves_insertion_order(){let m=realized_mapping(&[BlueprintElementId(17),BlueprintElementId(3),BlueprintElementId(42)]);assert_eq!(m.get(&BlueprintElementId(17)),Some(&0));assert_eq!(m.get(&BlueprintElementId(3)),Some(&1));assert_eq!(m.get(&BlueprintElementId(42)),Some(&2))}}