#[cfg(test)]
mod integration_tests {
    use crate::decision::{ActionKind, OutcomeKind};
    use crate::resources::{InternalBond, Material};
    use crate::state::{DevelopmentStage, Simulation};
    use crate::structure::{Bond, BondEndpoint, ConnectionEndpoint, Placement, StructuralUnit};
    fn structured_carbon_hydrogen()->Material{Material{parts:vec![("Carbon".into(),1.0),("Hydrogen".into(),1.0)],internal_bonds:vec![InternalBond{part_a:0,part_b:1}]}}
    #[test]fn fresh_organism_is_realized_from_its_genome_blueprint(){let o=Simulation::create_initial_organism();let blueprint=&o.genome.structural_blueprint;let expected_constituents=blueprint.elements.iter().map(|e|e.material.parts.len()).sum::<usize>();let expected_internal_bonds=blueprint.elements.iter().map(|e|e.material.internal_bonds.len()).sum::<usize>();assert_eq!(o.structure.units.len(),expected_constituents);assert_eq!(o.structure.bonds.len(),expected_internal_bonds+blueprint.connections.len());assert!(!o.structure.units.is_empty());assert!(o.stored_material.is_empty());assert!(matches!(o.development_stage,DevelopmentStage::Adult));assert!(o.decision_history.entries.is_empty())}
    #[test]fn initial_organism_is_adult_when_realized_mass_reaches_ninety_percent_of_mature_blueprint_size(){let o=Simulation::create_initial_organism();let mature=o.genome.structural_blueprint.structural_mass(&crate::resources::default_catalog());let realized=o.structural_mass(&crate::resources::default_catalog());assert!(realized/mature>=0.90);assert!(matches!(o.development_stage,DevelopmentStage::Adult))}
    #[test]fn adulthood_is_irreversible_after_structural_loss(){let mut s=Simulation::new(32,10.0);s.organisms[0].development_stage=DevelopmentStage::Adult;s.organisms[0].structure.units.clear();s.organisms[0].structure.bonds.clear();s.step();assert!(matches!(s.organisms[0].development_stage,DevelopmentStage::Adult))}
    #[test]fn storage_contains_discrete_independent_material_objects(){let mut o=Simulation::create_initial_organism();assert!(o.store_material(Material::free_base("Carbon",5.0)));assert_eq!(o.stored_material.materials.len(),5);assert_eq!(o.stored_material.count_unstructured(),5);assert_eq!(o.stored_material.total_amount(),5.0)}
    #[test]fn storage_preserves_a_compound_as_one_intact_object(){let mut o=Simulation::create_initial_organism();let m=structured_carbon_hydrogen();assert!(o.store_material(m.clone()));assert_eq!(o.stored_material.materials,vec![m]);assert_eq!(o.stored_material.count_structured(),1)}
    #[test]fn acquire_moves_one_free_unit_into_storage_and_conserves_material_when_vents_are_disabled(){let mut s=Simulation::new(21,10.0);s.environment.vents.clear();let i=s.environment.field.index_for_position(500.0,500.0).unwrap();s.environment.field.cells[i].materials.clear();s.environment.field.deposit_at_index(i,Material::free_base("Carbon",10.0));s.organisms[0].decision_history.record(ActionKind::Acquire,Some(format!("target:{i}")),OutcomeKind::Beneficial);let before=s.total_material_in_system();s.step();let after=s.total_material_in_system();assert!((after-before).abs()<1e-3);assert_eq!(s.organisms[0].stored_material.total_amount(),1.0)}
    #[test]fn acquire_accepts_and_preserves_structured_material(){let mut s=Simulation::new(23,10.0);s.environment.vents.clear();let i=s.environment.field.index_for_position(500.0,500.0).unwrap();s.environment.field.cells[i].materials.clear();let m=structured_carbon_hydrogen();s.environment.field.deposit_at_index(i,m.clone());s.organisms[0].decision_history.record(ActionKind::Acquire,Some(format!("target:{i}")),OutcomeKind::Beneficial);s.step();assert!(s.environment.field.cells[i].materials.is_empty());assert_eq!(s.organisms[0].stored_material.materials,vec![m])}
    #[test]fn acquire_only_considers_the_currently_occupied_field_cell(){let mut s=Simulation::new(22,10.0);s.environment.vents.clear();let i=s.environment.field.index_for_position(600.0,500.0).unwrap();s.environment.field.deposit_at_index(i,Material::free_base("Carbon",10.0));s.step();assert!(s.organisms[0].stored_material.is_empty())}
    #[test]fn structural_material_is_not_opened_by_storage(){let mut o=Simulation::create_initial_organism();assert!(o.store_material(structured_carbon_hydrogen()));assert_eq!(o.stored_material.count_unstructured(),0);assert_eq!(o.stored_material.count_structured(),1)}
    #[test]fn fresh_simulation_material_flow_remains_finite_with_direct_vent_sources(){let mut s=Simulation::new(1,10.0);for _ in 0..300{s.step();}assert!(s.total_material_in_system().is_finite());assert!(s.total_material_in_system()>0.0)}
    fn add_test_break_bond(s:&mut Simulation){s.organisms[0].structure.bonds.clear();let a=s.organisms[0].structure.add_unit(StructuralUnit::new("Carbon",Placement{x:500.0,y:500.0,rotation_radians:0.0}));let b=s.organisms[0].structure.add_unit(StructuralUnit::new("Methane",Placement{x:501.0,y:500.0,rotation_radians:0.0}));let id_a=s.organisms[0].structure.physical_id(a).unwrap();let id_b=s.organisms[0].structure.physical_id(b).unwrap();s.organisms[0].structure.push_bond_unchecked(Bond{endpoint_a:BondEndpoint::new(id_a,ConnectionEndpoint::Corner{point_index:0}),endpoint_b:BondEndpoint::new(id_b,ConnectionEndpoint::Corner{point_index:0}),strength:0.8,bond_energy:12.5});}
    #[test]fn break_action_starts_a_transformation_before_resolution(){let mut s=Simulation::new(7,10.0);add_test_break_bond(&mut s);s.step();assert_eq!(s.organisms[0].structure.bonds.len(),1);assert!(s.organisms[0].active_transformation_id.is_some())}
    #[test]fn break_resolution_changes_state_on_expected_tick(){let mut s=Simulation::new(7,10.0);add_test_break_bond(&mut s);s.step();s.step();s.step();let a_index=s.organisms[0].structure.units.len()-2;let b_index=s.organisms[0].structure.units.len()-1;let a=s.organisms[0].structure.units[a_index].properties(&s.environment.catalog).unwrap();let b=s.organisms[0].structure.units[b_index].properties(&s.environment.catalog).unwrap();let candidate=crate::contact::connection_pair_candidates(&s.organisms[0].structure,a_index,b_index,&s.environment.catalog).into_iter().find(|c|c.endpoint_a==ConnectionEndpoint::Corner{point_index:0}&&c.endpoint_b==ConnectionEndpoint::Corner{point_index:0}).expect("test bond endpoints must remain resolvable");let water=s.organisms[0].occupied_cells.first().and_then(|p|s.environment.field.index_for_position(p.x,p.y)).map(|i|s.environment.field.cells[i].materials.iter().flat_map(|m|m.parts.iter()).filter(|(name,_)|name=="Water").map(|(_,amount)|*amount).sum::<f64>()).unwrap_or(0.0);let formation_interaction=crate::combine::experimental_interaction(a,b,candidate,water);let break_interaction=-formation_interaction.signed_value;let work=crate::transformation::break_work_cost(a,b,crate::math::complexity(2.0));let maintenance=s.organisms[0].structural_mass(&s.environment.catalog)*crate::state::MAINTENANCE_ENERGY_PER_MASS;let expected=12.5+break_interaction-work-maintenance;assert!(s.organisms[0].structure.bonds.is_empty());assert!((s.organisms[0].usable_energy-expected).abs()<1e-12);assert!(s.organisms[0].decision_history.has_knowledge(ActionKind::Break,Some("bond:0"))) }
}
