//! Structural material owned by a physical structural unit.
use serde::{Deserialize,Serialize};use std::collections::{HashMap,HashSet,VecDeque};use crate::attachment::{AttachmentFeature,ConstituentId};use crate::resources::{BaseResource,ConnectionPoint,ConnectionSites,Form,Material,ResourceProperties,Shape};use crate::structure::Placement;
#[derive(Serialize,Deserialize,Clone,Debug,PartialEq)]pub struct StructuralMaterial{pub material:Material}
impl StructuralMaterial{
pub fn from_material(material:Material)->Option<Self>{if !material.is_valid()||material.is_empty(){return None}if !material.is_structured()&&(material.composition().len()!=1||(material.total_amount()-1.0).abs()>f64::EPSILON){return None}Some(Self{material})}pub fn single(resource_name:impl Into<String>)->Self{Self{material:Material::free_base(resource_name,1.0)}}pub fn material(&self)->&Material{&self.material}pub fn composition(&self)->&[crate::resources::MaterialComponent]{self.material.composition()}pub fn structure(&self)->Option<&crate::material_structure::MaterialStructure>{self.material.structure()}pub fn total_amount(&self)->f64{self.material.total_amount()}pub fn mass(&self,catalog:&[BaseResource])->f64{self.material.mass(catalog)}pub fn weighted_properties(&self,catalog:&[BaseResource])->ResourceProperties{self.material.weighted_properties(catalog)}pub fn is_composite(&self)->bool{self.material.structure().map_or(false,|s|s.constituents.len()>1)}pub fn is_valid(&self)->bool{self.material.is_valid()&&!self.material.is_empty()}
pub fn resolves_in_catalog(&self,catalog:&[BaseResource])->bool{if let Some(s)=self.material.structure(){s.constituents.iter().all(|c|catalog.iter().any(|b|b.name==c.resource))}else{self.material.composition().iter().all(|c|catalog.iter().any(|b|b.name==c.resource))}}
fn rigid_constituent_placements(&self,catalog:&[BaseResource])->Option<HashMap<ConstituentId,(Form,Placement)>>{let s=self.material.structure()?;let mut rigid=HashMap::new();for c in &s.constituents{let b=catalog.iter().find(|b|b.name==c.resource)?;if b.shape.form.rigid_bounding_radius().is_some(){rigid.insert(c.id,b.shape.form.clone());}}if rigid.is_empty(){return Some(HashMap::new())}let root=s.constituents.iter().find(|c|rigid.contains_key(&c.id))?.id;let mut placements=HashMap::new();placements.insert(root,Placement{x:0.0,y:0.0,rotation_radians:0.0});let mut q=VecDeque::from([root]);while let Some(cur)=q.pop_front(){let cp=*placements.get(&cur)?;for bond in &s.internal_bonds{let(n,cf,nf)=if bond.a.constituent==cur{(bond.b.constituent,bond.a.feature,bond.b.feature)}else if bond.b.constituent==cur{(bond.a.constituent,bond.b.feature,bond.a.feature)}else{continue};if !rigid.contains_key(&n)||placements.contains_key(&n){continue}let(AttachmentFeature::Discrete(_),AttachmentFeature::Discrete(_))=(cf,nf)else{continue};let cr=catalog.iter().find(|r|r.name==s.constituents.iter().find(|c|c.id==cur)?.resource)?;let nr=catalog.iter().find(|r|r.name==s.constituents.iter().find(|c|c.id==n)?.resource)?;let ca=crate::attachment::ConstituentAttachment{constituent:cur,feature:cf};let na=crate::attachment::ConstituentAttachment{constituent:n,feature:nf};let(_,local)=crate::material_realization::resolve_rigid_attachment(cr,&ca,nr,&na)?;let(sin,cos)=cp.rotation_radians.sin_cos();placements.insert(n,Placement{x:cp.x+local.x*cos-local.y*sin,y:cp.y+local.x*sin+local.y*cos,rotation_radians:cp.rotation_radians+local.rotation_radians});q.push_back(n)}}Some(placements.into_iter().filter_map(|(id,p)|rigid.remove(&id).map(|f|(id,(f,p)))).collect())}
pub fn rigid_constituent_placement(&self,id:ConstituentId,catalog:&[BaseResource])->Option<Placement>{self.rigid_constituent_placements(catalog)?.get(&id).map(|(_,p)|*p)}
pub fn constituent_resource(&self,id:ConstituentId)->Option<&str>{self.material.structure()?.constituents.iter().find(|c|c.id==id).map(|c|c.resource.as_str())}
pub fn connection_site_for_constituent_feature(&self,id:ConstituentId,feature:u32,catalog:&[BaseResource])->Option<usize>{let sites=self.connection_sites(catalog)?;let ConnectionSites::Corners(points)=sites else{return None};let local=self.rigid_constituent_placement(id,catalog)?;let resource_name=self.constituent_resource(id)?;let resource=catalog.iter().find(|r|r.name==resource_name)?;let ConnectionSites::Corners(source)=resource.shape.connection_sites()else{return None};let source_point=*source.get(feature as usize)?;let(sin,cos)=local.rotation_radians.sin_cos();let target=ConnectionPoint{x:local.x+source_point.x*cos-source_point.y*sin,y:local.y+source_point.x*sin+source_point.y*cos,direction_radians:source_point.direction_radians+local.rotation_radians};points.iter().position(|p|(p.x-target.x).hypot(p.y-target.y)<=1e-9)}
pub fn physical_rigid_parts(&self,catalog:&[BaseResource])->Option<Vec<(Form,Placement)>>{if let Some(parts)=self.rigid_constituent_placements(catalog){return Some(self.material.structure()?.constituents.iter().filter_map(|c|parts.get(&c.id).cloned()).collect::<Vec<_>>())}let[c]=self.material.composition()else{return None};if(c.amount-1.0).abs()>f64::EPSILON{return None}let b=catalog.iter().find(|b|b.name==c.resource)?;Some(if b.shape.form.rigid_bounding_radius().is_some(){vec![(b.shape.form.clone(),Placement{x:0.0,y:0.0,rotation_radians:0.0})]}else{Vec::new()})}
pub fn connection_sites(&self,catalog:&[BaseResource])->Option<ConnectionSites>{if !self.material.is_structured(){let[c]=self.material.composition()else{return None};if(c.amount-1.0).abs()>f64::EPSILON{return None}return catalog.iter().find(|b|b.name==c.resource).map(|b|b.shape.connection_sites())}let s=self.material.structure()?;let placements=self.rigid_constituent_placements(catalog)?;let mut used=HashSet::<(ConstituentId,AttachmentFeature)>::new();for b in &s.internal_bonds{used.insert((b.a.constituent,b.a.feature));used.insert((b.b.constituent,b.b.feature));}let mut out=Vec::new();for c in &s.constituents{let Some((_,p))=placements.get(&c.id)else{continue};let Some(resource)=catalog.iter().find(|r|r.name==c.resource)else{return None};let ConnectionSites::Corners(points)=resource.shape.connection_sites()else{continue};let(sin,cos)=p.rotation_radians.sin_cos();for(i,point)in points.into_iter().enumerate(){if used.contains(&(c.id,AttachmentFeature::Discrete(i as u32)){continue}out.push(ConnectionPoint{x:p.x+point.x*cos-point.y*sin,y:p.y+point.x*sin+point.y*cos,direction_radians:point.direction_radians+p.rotation_radians})}}if out.is_empty(){Some(ConnectionSites::Undetermined)}else{Some(ConnectionSites::Corners(out))}}
pub fn shape<'a>(&self,catalog:&'a[BaseResource])->Option<&'a Shape>{if self.material.is_structured(){None}else{let[c]=self.material.composition()else{return None};if(c.amount-1.0).abs()>f64::EPSILON{return None}catalog.iter().find(|b|b.name==c.resource).map(|b|&b.shape)}}}
