use crate::decision::{ActionKind, OutcomeKind};
use crate::decision_runtime::ActionCandidate;
use crate::state::{ActiveTransformation, EnergyLedger, Environment, Organism, Simulation};

pub(crate) fn water_field_amount_at_bond(environment:&Environment,structure:&crate::structure::OrganismStructure,bond:&crate::structure::Bond)->f64{let Some(unit_a)=structure.units.get(bond.endpoint_a.unit_index)else{return 0.0};let Some(unit_b)=structure.units.get(bond.endpoint_b.unit_index)else{return 0.0};let Some(world_a)=bond.endpoint_a.location.world_point(unit_a,&environment.catalog)else{return 0.0};let Some(world_b)=bond.endpoint_b.location.world_point(unit_b,&environment.catalog)else{return 0.0};let x=(world_a.x+world_b.x)*0.5;let y=(world_a.y+world_b.y)*0.5;environment.field.index_for_position(x,y).map(|index|environment.field.cells[index].materials.iter().flat_map(|material|material.parts.iter()).filter(|(name,_)|name=="Water").map(|(_,amount)|*amount).sum()).unwrap_or(0.0)}

pub(crate) struct BreakResolution{pub(crate) bond_energy:f64,pub(crate) break_interaction_energy:f64,pub(crate) work:f64,pub(crate) net_energy:f64}

pub(crate) fn calculate_break_resolution(a:crate::resources::ResourceProperties,b:crate::resources::ResourceProperties,candidate:&crate::contact::ConnectionPairCandidate,bond_energy:f64,complexity:f64,water_amount:f64)->Option<BreakResolution>{if !bond_energy.is_finite()||bond_energy<0.0||!water_amount.is_finite()||water_amount<0.0{return None}let work=break_work_cost(a,b,complexity);if !work.is_finite()||work<0.0{return None}let formation_interaction=crate::combine::experimental_interaction(a,b,candidate,water_amount);let break_interaction_energy=-formation_interaction.signed_value;if !break_interaction_energy.is_finite(){return None}let net=bond_energy+break_interaction_energy-work;if !net.is_finite(){return None}Some(BreakResolution{bond_energy,break_interaction_energy,work,net_energy:net})}

fn settle_break_energy(organism:&mut Organism,bond:crate::structure::Bond,resolution:&BreakResolution,ledger:&mut EnergyLedger)->bool{let net=resolution.net_energy;if net<0.0&&organism.usable_energy+f64::EPSILON< -net{return false}if organism.structure.break_matching_bond(bond).is_none(){return false}organism.add_transaction_stress(resolution.work);if resolution.work>0.0{ledger.total_heat_dissipated+=resolution.work}organism.usable_energy+=net;if resolution.bond_energy>0.0{ledger.total_potential_energy_released+=resolution.bond_energy;}if resolution.break_interaction_energy>0.0{ledger.total_potential_energy_released+=resolution.break_interaction_energy;}if net>0.0{ledger.total_usable_energy_gained+=net;}true}

pub(crate) fn resolve_stress_break(organism:&mut Organism,environment:&Environment,ledger:&mut EnergyLedger)->bool{let Some((_,target))=organism.structure.bonds.iter().enumerate().min_by(|(_,a),(_,b)|a.strength.partial_cmp(&b.strength).unwrap_or(std::cmp::Ordering::Equal))else{return false};let target=*target;let Some(a)=organism.structure.units.get(target.endpoint_a.unit_index).and_then(|u|u.properties(&environment.catalog))else{return false};let Some(b)=organism.structure.units.get(target.endpoint_b.unit_index).and_then(|u|u.properties(&environment.catalog))else{return false};let complexity=crate::math::complexity(2.0);let Some(candidate)=crate::contact::connection_pair_candidate_for_endpoints(&organism.structure,target.endpoint_a.unit_index,target.endpoint_b.unit_index,target.endpoint_a.location,target.endpoint_b.location,&environment.catalog)else{return false};let resolution=match calculate_break_resolution(a,b,candidate,target.bond_energy,complexity,water_field_amount_at_bond(environment,&organism.structure,&target)){Some(x)=>x,None=>return false};settle_break_energy(organism,target,&resolution,ledger)}

impl Simulation {
 pub(crate) fn try_start_transformation(organism:&mut Organism,catalog:&[crate::resources::BaseResource],next_id:&mut u64,decision:&ActionCandidate)->Option<ActiveTransformation>{if decision.action!=ActionKind::Break||organism.active_transformation_id.is_some(){return None}let key=decision.context_key.as_deref()?;let index=key.strip_prefix("bond:")?.parse::<usize>().ok()?;let bond=*organism.structure.bonds.get(index)?;if !bond.bond_energy.is_finite()||bond.bond_energy<0.0{return None}let _a=organism.structure.units.get(bond.endpoint_a.unit_index)?.properties(catalog)?;let _b=organism.structure.units.get(bond.endpoint_b.unit_index)?.properties(catalog)?;let complexity=crate::math::complexity(2.0);let duration=1_u64.max(complexity.ceil() as u64);let t=ActiveTransformation{id:*next_id,organism_id:organism.id.clone(),kind:crate::state::TransformationKind::Break,material:crate::resources::Material::free_base("",0.0),bond:Some(bond),complexity,duration_ticks:duration,remaining_ticks:duration,decision_context_key:decision.context_key.clone()};*next_id+=1;organism.active_transformation_id=Some(t.id);Some(t)}
 pub(crate) fn resolve_transformation(transformation:&ActiveTransformation,organism:&mut Organism,environment:&mut Environment,ledger:&mut EnergyLedger){let Some(target)=transformation.bond else{organism.active_transformation_id=None;return};if target.endpoint_a.unit_index>=organism.structure.units.len()||target.endpoint_b.unit_index>=organism.structure.units.len(){organism.active_transformation_id=None;return}if !organism.structure.bonds.iter().any(|b|b.has_same_identity(&target)){organism.active_transformation_id=None;return}let a=match organism.structure.units[target.endpoint_a.unit_index].properties(&environment.catalog){Some(x)=>x,None=>{organism.active_transformation_id=None;return}};let b=match organism.structure.units[target.endpoint_b.unit_index].properties(&environment.catalog){Some(x)=>x,None=>{organism.active_transformation_id=None;return}};let candidate=match crate::contact::connection_pair_candidate_for_endpoints(&organism.structure,target.endpoint_a.unit_index,target.endpoint_b.unit_index,target.endpoint_a.location,target.endpoint_b.location,&environment.catalog){Some(x)=>x,None=>{organism.active_transformation_id=None;return}};let resolution=match calculate_break_resolution(a,b,candidate,target.bond_energy,transformation.complexity,water_field_amount_at_bond(environment,&organism.structure,&target)){Some(x)=>x,None=>{organism.active_transformation_id=None;return}};let net=resolution.net_energy;if net<0.0&&organism.usable_energy+f64::EPSILON< -net{organism.active_transformation_id=None;let candidate=ActionCandidate{action:ActionKind::Break,context_key:transformation.decision_context_key.clone()};crate::decision_runtime::record_outcome(&mut organism.decision_history,&candidate,OutcomeKind::Harmful);return}if organism.structure.break_matching_bond(target).is_none(){organism.active_transformation_id=None;return}organism.add_transaction_stress(resolution.work);if resolution.work>0.0{ledger.total_heat_dissipated+=resolution.work}organism.usable_energy+=net;if resolution.bond_energy>0.0{ledger.total_potential_energy_released+=resolution.bond_energy;}if resolution.break_interaction_energy>0.0{ledger.total_potential_energy_released+=resolution.break_interaction_energy;}if net>0.0{ledger.total_usable_energy_gained+=net;}organism.active_transformation_id=None;let outcome=if net>f64::EPSILON{OutcomeKind::Beneficial}else if net< -f64::EPSILON{OutcomeKind::Harmful}else{OutcomeKind::Neutral};let candidate=ActionCandidate{action:ActionKind::Break,context_key:transformation.decision_context_key.clone()};crate::decision_runtime::record_outcome(&mut organism.decision_history,&candidate,outcome);if net>0.0{let reinforcement=(net*organism.genome.memory_strength()).clamp(0.0,1.0);let(x,y)=organism.occupied_cells.first().map(|p|(p.x,p.y)).unwrap_or((0.0,0.0));reinforce_memory_point(organism,x,y,reinforcement)}}
}

pub(crate) fn break_work_cost(a:crate::resources::ResourceProperties,b:crate::resources::ResourceProperties,complexity:f64)->f64{crate::combine::bond_strength(a,b)*complexity.max(0.0)}
pub(crate) fn reinforce_memory_point(organism:&mut Organism,x:f64,y:f64,reinforcement:f64){if let Some(point)=organism.memory.iter_mut().find(|p|(p.x-x).abs()<f64::EPSILON&&(p.y-y).abs()<f64::EPSILON){point.strength=crate::math::clamp01(point.strength+reinforcement)}else{organism.memory.push(crate::state::MemoryPoint{x,y,strength:crate::math::clamp01(reinforcement)})}}
#[cfg(test)]mod tests{use super::*;fn fixture()->(crate::resources::ResourceProperties,crate::contact::ConnectionPairCandidate){let p=crate::resources::ResourceProperties{mass:1.0,potential_energy:1.0,reactivity:0.0,cohesion:1.0};let c=crate::contact::ConnectionPairCandidate{unit_a:0,unit_b:1,endpoint_a:crate::structure::ConnectionEndpoint::Corner{point_index:0},endpoint_b:crate::structure::ConnectionEndpoint::Corner{point_index:0},world_a:crate::state::Position{x:0.0,y:0.0},world_b:crate::state::Position{x:1.0,y:0.0},distance:1.0,interaction:1.0,score:1.0};(p,c)}#[test]fn break_resolution_supports_positive_zero_and_negative_net_results(){let(a,c)=fixture();let positive=calculate_break_resolution(a,a,&c,10.0,1.0,0.0).unwrap();let zero=calculate_break_resolution(a,a,&c,1.0,1.0,0.0).unwrap();let negative=calculate_break_resolution(a,a,&c,1.0,2.0,0.0).unwrap();assert!(positive.net_energy>0.0);assert_eq!(zero.net_energy,0.0);assert!(negative.net_energy<0.0)}#[test]fn invalid_break_energy_is_rejected(){let(a,c)=fixture();assert!(calculate_break_resolution(a,a,&c,-1.0,1.0,0.0).is_none());assert!(calculate_break_resolution(a,a,&c,1.0,1.0,f64::NAN).is_none());assert!(calculate_break_resolution(a,a,&c,1.0,-1.0,0.0).is_none())}}