(() => {
const NS='http://www.w3.org/2000/svg';
const S={items:[],offset:0,limit:250,selected:null,detail:null,view:null,drag:null};
const c=document.getElementById('canvas'),diag=document.getElementById('diagnostics'),list=document.getElementById('formation-list'),details=document.getElementById('details'),summary=document.getElementById('summary'),search=document.getElementById('search'),size=document.getElementById('size');
function diagnostic(msg){if(diag)diag.textContent=msg}function esc(s){return String(s).replace(/[&<>"]/g,a=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[a]))}
function fmt(v){return Number.isFinite(v)?Number(v).toFixed(4):'—'}
function names(f){return (f.resources||f.constituents||[]).map(c=>typeof c==='string'?c:c.resource).join(' + ')}
function card(k,v){return '<div class="card"><b>'+esc(k)+'</b><span>'+esc(v)+'</span></div>'}
function el(tag,attrs={}){const e=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,v);return e}
async function load(){diagnostic('JS running\nSVG size: '+c.clientWidth+' × '+c.clientHeight+'\nLoading formation catalogue…');const p=new URLSearchParams({offset:String(S.offset),limit:String(S.limit)}),q=search.value.trim();if(q)p.set('search',q);if(size.value!=='all')p.set('size',size.value);const r=await fetch('/geometry/api/formations?'+p);if(!r.ok){summary.textContent='Library unavailable';return}const d=await r.json();S.items=d.formations||[];diagnostic('Catalogue loaded\nSVG size: '+c.clientWidth+' × '+c.clientHeight+'\nFormations returned: '+S.items.length+'\nTotal: '+d.total);S.total=d.total||0;summary.textContent='Showing '+(S.offset+1)+'–'+(S.offset+S.items.length)+' of '+d.total+' formations · library entries: '+d.library_entries;renderList();if(S.items.length&&!S.selected)select(S.items[0].signature)}
function renderList(){list.replaceChildren();for(const i of S.items){const e=document.createElement('div');e.className='formation'+(i.signature===S.selected?' selected':'');e.innerHTML='<strong>'+esc(names(i))+'</strong><small>'+i.constituent_count+' constituent'+(i.constituent_count===1?'':'s')+' · '+i.bond_count+' bonds</small>';e.onclick=()=>select(i.signature);list.appendChild(e)}}
async function select(sig){S.selected=sig;S.detail=null;diagnostic('Formation selected\nSVG size: '+c.clientWidth+' × '+c.clientHeight+'\nSignature: '+sig+'\nFetching exact formation…');renderList();drawMessage('Loading formation…');try{const r=await fetch('/geometry/api/formation?signature='+encodeURIComponent(sig));if(!r.ok)throw new Error('HTTP '+r.status);const d=await r.json();if(S.selected!==sig)return;if(!d.formation||!Array.isArray(d.formation.constituents))throw new Error('Invalid formation response');S.detail=d;fit();renderDetails();draw();diagnostic('Formation loaded\nSVG size: '+c.clientWidth+' × '+c.clientHeight+'\nConstituents: '+d.formation.constituents.length+'\nViewBox: '+[S.view.x,S.view.y,S.view.w,S.view.h].join(' ')+'\nFirst form: '+JSON.stringify(d.formation.constituents[0]?.form)+'\nFirst placement: '+JSON.stringify(d.formation.constituents[0]?.placement));}catch(e){diagnostic('ERROR\n'+e.message);if(S.selected===sig){details.innerHTML='<div class="muted">Could not load formation: '+esc(e.message)+'</div>';drawMessage('Could not load formation')}}}
function renderDetails(){const f=S.detail.formation;let h='<div class="detail-grid">'+card('Constituents',f.constituents.length)+card('Bonds',f.bonds.length)+card('Signature',f.signature.slice(0,32)+'…')+card('Schema',f.schema_version)+'</div><table><thead><tr><th>#</th><th>Resource</th><th>X</th><th>Y</th><th>Rotation</th></tr></thead><tbody>';f.constituents.forEach((a,i)=>h+='<tr><td>'+i+'</td><td>'+esc(a.resource)+'</td><td>'+fmt(a.placement.x)+'</td><td>'+fmt(a.placement.y)+'</td><td>'+fmt(a.placement.rotation_radians)+'</td></tr>');h+='</tbody></table><div class="family"><h3>Bond topology</h3><div class="muted">'+(f.bonds.length?f.bonds.map(b=>b.constituent_a+' ↔ '+b.constituent_b).join(' · '):'No bonds')+'</div></div>';for(const[label,key]of[['Rigid edge families','rigid_contact_families'],['Rigid point-contact families','rigid_point_contact_families'],['Rigid vertex-contact families','rigid_vertex_contact_families'],['Fluid/contact families','contact_families'],['Fluid boundary families','fluid_boundary_families']]){const a=S.detail[key]||[];h+='<div class="family"><h3>'+label+' ('+a.length+')</h3><div class="muted">'+(a.length?a.slice(0,100).map(v=>esc(JSON.stringify(v))).join('<br>'):'None recorded for this formation.')+(a.length>100?'<br>…':'')+'</div></div>'}details.innerHTML=h}
function geo(raw){const f=raw?.form??raw;if(!f)return null;if(f.Circle&&Number.isFinite(f.Circle.radius))return['c',f.Circle.radius];if(f.Line&&Number.isFinite(f.Line.length))return['l',f.Line.length];if(f.Rectangle&&Number.isFinite(f.Rectangle.width)&&Number.isFinite(f.Rectangle.height))return['p',[[-f.Rectangle.width/2,-f.Rectangle.height/2],[f.Rectangle.width/2,-f.Rectangle.height/2],[f.Rectangle.width/2,f.Rectangle.height/2],[-f.Rectangle.width/2,f.Rectangle.height/2]]];if(f.RegularPolygon&&Number.isInteger(f.RegularPolygon.sides)&&Number.isFinite(f.RegularPolygon.radius)){const n=f.RegularPolygon.sides,r=f.RegularPolygon.radius;return['p',Array.from({length:n},(_,i)=>{const a=i*2*Math.PI/n;return[r*Math.cos(a),r*Math.sin(a)]})]}if(f.Polygon&&Array.isArray(f.Polygon.vertices))return['p',f.Polygon.vertices];if(f.Fluid?.boundary)return['p',f.Fluid.boundary];if(f.Fluid&&Number.isFinite(f.Fluid.nominal_area))return['c',Math.sqrt(f.Fluid.nominal_area/Math.PI)];return null}
function bounds(){let a=Infinity,b=Infinity,d=-Infinity,e=-Infinity;for(const q of S.detail.formation.constituents){const g=geo(q),p=q.placement;if(!g)continue;const z=p.rotation_radians,co=Math.cos(z),si=Math.sin(z);if(g[0]==='c'){const r=g[1];a=Math.min(a,p.x-r);d=Math.max(d,p.x+r);b=Math.min(b,p.y-r);e=Math.max(e,p.y+r)}else if(g[0]==='l'){for(const v of [[-g[1]/2,0],[g[1]/2,0]]){const X=p.x+v[0]*co-v[1]*si,Y=p.y+v[0]*si+v[1]*co;a=Math.min(a,X);d=Math.max(d,X);b=Math.min(b,Y);e=Math.max(e,Y)}}else for(const v of g[1]){const X=p.x+v[0]*co-v[1]*si,Y=p.y+v[0]*si+v[1]*co;a=Math.min(a,X);d=Math.max(d,X);b=Math.min(b,Y);e=Math.max(e,Y)}}return[a,b,d,e]}
function fit(){const b=bounds();if(!b.every(Number.isFinite))return;const pad=Math.max((b[2]-b[0])*0.1,(b[3]-b[1])*0.1,0.5);S.view={x:b[0]-pad,y:-(b[3]+pad),w:(b[2]-b[0])+2*pad,h:(b[3]-b[1])+2*pad};c.setAttribute('viewBox',[S.view.x,S.view.y,S.view.w,S.view.h].join(' '))}
function drawMessage(msg){c.replaceChildren();const t=el('text',{x:'50%',y:'50%','text-anchor':'middle',fill:'#aaa','font-size':'18','font-family':'system-ui'});t.textContent=msg;c.appendChild(t)}
function draw(){if(!S.detail){diagnostic('Drawing message\nSVG size: '+c.clientWidth+' × '+c.clientHeight);drawMessage(S.selected?'Loading formation…':'Select a formation');return}c.replaceChildren();const f=S.detail.formation;const bg=el('rect',{x:S.view.x,y:S.view.y,width:S.view.w,height:S.view.h,fill:'#0d0d0d'});c.appendChild(bg);const pal=['#5bc0eb','#f6bd60','#84a59d','#f28482','#cdb4db','#90be6d','#f7ede2'];f.constituents.forEach((a,i)=>{const g=geo(a),p=a.placement;if(!g)return;const G=el('g',{transform:'translate('+p.x+' '+(-p.y)+') rotate('+(-p.rotation_radians*180/Math.PI)+')'});const stroke=pal[i%pal.length];if(g[0]==='c'){G.appendChild(el('circle',{r:g[1],fill:stroke, 'fill-opacity':'.2',stroke,'stroke-width':'.03'}))}else if(g[0]==='l'){G.appendChild(el('line',{x1:-g[1]/2,y1:0,x2:g[1]/2,y2:0,stroke,'stroke-width':'.03'}))}else{G.appendChild(el('polygon',{points:g[1].map(v=>v[0]+','+v[1]).join(' '),fill:stroke,'fill-opacity':'.2',stroke,'stroke-width':'.03'}))}c.appendChild(G)});const label=el('text',{x:S.view.x+0.02*S.view.w,y:S.view.y+0.05*S.view.h,fill:'#aaa','font-size':Math.max(S.view.w,S.view.h)*.025,'font-family':'system-ui'});label.textContent='Rendering '+f.constituents.length+' constituent'+(f.constituents.length===1?'':'s');c.appendChild(label);diagnostic('Draw complete\nSVG size: '+c.clientWidth+' × '+c.clientHeight+'\nViewBox: '+[S.view.x,S.view.y,S.view.w,S.view.h].join(' ')+'\nDOM children: '+c.childNodes.length+'\nFirst child: '+c.firstElementChild?.tagName+'\nFirst shape: '+c.querySelector('circle,polygon,line')?.outerHTML)}
function zoomAt(factor,cx,cy){if(!S.view)return;const vx=S.view.x+(cx/c.clientWidth)*S.view.w,vy=S.view.y+(cy/c.clientHeight)*S.view.h;const nw=S.view.w/factor,nh=S.view.h/factor;S.view={x:vx-(cx/c.clientWidth)*nw,y:vy-(cy/c.clientHeight)*nh,w:nw,h:nh};c.setAttribute('viewBox',[S.view.x,S.view.y,S.view.w,S.view.h].join(' '));draw()}
c.addEventListener('wheel',e=>{e.preventDefault();zoomAt(Math.exp(-e.deltaY*.001),e.offsetX,e.offsetY)},{passive:false});
c.addEventListener('pointerdown',e=>{c.setPointerCapture(e.pointerId);S.drag={x:e.clientX,y:e.clientY,view:{...S.view}}});
c.addEventListener('pointermove',e=>{if(!S.drag||!S.view)return;const r=c.getBoundingClientRect(),dx=(e.clientX-S.drag.x)/r.width*S.drag.view.w,dy=(e.clientY-S.drag.y)/r.height*S.drag.view.h;S.view={...S.drag.view,x:S.drag.view.x-dx,y:S.drag.view.y+dy};c.setAttribute('viewBox',[S.view.x,S.view.y,S.view.w,S.view.h].join(' '));draw()});
c.addEventListener('pointerup',()=>S.drag=null);addEventListener('keydown',e=>{if(e.key.toLowerCase()==='r'){fit();draw()}});
document.getElementById('refresh').onclick=load;document.getElementById('prev').onclick=()=>{S.offset=Math.max(0,S.offset-S.limit);S.selected=null;load()};document.getElementById('next').onclick=()=>{if(S.offset+S.items.length>=S.total)return;S.offset+=S.limit;S.selected=null;load()};search.addEventListener('keydown',e=>{if(e.key==='Enter'){S.offset=0;load()}});size.onchange=()=>{S.offset=0;load()};setInterval(load,5000);drawMessage('Loading library…');load();
})();