(() => {
const S={items:[],offset:0,limit:250,selected:null,zoom:1,pan:{x:0,y:0},drag:null};const c=document.getElementById('canvas'),x=c.getContext('2d'),list=document.getElementById('formation-list'),details=document.getElementById('details'),summary=document.getElementById('summary'),search=document.getElementById('search'),size=document.getElementById('size');
function resize(){c.width=c.clientWidth*devicePixelRatio;c.height=c.clientHeight*devicePixelRatio;x.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);draw()}addEventListener('resize',resize);
function esc(s){return String(s).replace(/[&<>"]/g,a=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[a]))}function fmt(v){return Number.isFinite(v)?Number(v).toFixed(4):'—'}function names(f){return (f.resources||f.constituents||[]).map(c=>typeof c==='string'?c:c.resource).join(' + ')}function card(k,v){return '<div class="card"><b>'+esc(k)+'</b><span>'+esc(v)+'</span></div>'}
async function load(){const p=new URLSearchParams({offset:String(S.offset),limit:String(S.limit)}),q=search.value.trim();if(q)p.set('search',q);if(size.value!=='all')p.set('size',size.value);const r=await fetch('/geometry/api/formations?'+p);if(!r.ok){summary.textContent='Library unavailable';return}const d=await r.json();S.items=d.formations||[];S.total=d.total||0;summary.textContent='Showing '+(S.offset+1)+'–'+(S.offset+S.items.length)+' of '+d.total+' formations · library entries: '+d.library_entries;renderList();if(S.items.length&&!S.selected)select(S.items[0].signature);else if(S.selected&&S.items.some(i=>i.signature===S.selected))renderList()}
function renderList(){list.replaceChildren();for(const i of S.items){const e=document.createElement('div');e.className='formation'+(i.signature===S.selected?' selected':'');e.innerHTML='<strong>'+esc(names(i))+'</strong><small>'+i.constituent_count+' constituent'+(i.constituent_count===1?'':'s')+' · '+i.bond_count+' bonds</small>';e.onclick=()=>select(i.signature);list.appendChild(e)}}

async function select(sig){S.selected=sig;renderList();const r=await fetch('/geometry/api/formation?signature='+encodeURIComponent(sig));if(!r.ok){if(S.selected===sig)details.innerHTML='<div class="muted">Formation unavailable.</div>';return}const d=await r.json();if(S.selected!==sig)return;S.detail=d;fit();renderDetails();draw()}
function renderDetails(){const f=S.detail.formation;let h='<div class="detail-grid">'+card('Constituents',f.constituents.length)+card('Bonds',f.bonds.length)+card('Signature',f.signature.slice(0,32)+'…')+card('Schema',f.schema_version)+'</div><table><thead><tr><th>#</th><th>Resource</th><th>X</th><th>Y</th><th>Rotation</th></tr></thead><tbody>';f.constituents.forEach((a,i)=>h+='<tr><td>'+i+'</td><td>'+esc(a.resource)+'</td><td>'+fmt(a.placement.x)+'</td><td>'+fmt(a.placement.y)+'</td><td>'+fmt(a.placement.rotation_radians)+'</td></tr>');h+='</tbody></table><div class="family"><h3>Bond topology</h3><div class="muted">'+(f.bonds.length?f.bonds.map(b=>b.constituent_a+' ↔ '+b.constituent_b).join(' · '):'No bonds')+'</div></div>';for(const [label,key] of [['Rigid edge families','rigid_contact_families'],['Rigid point-contact families','rigid_point_contact_families'],['Rigid vertex-contact families','rigid_vertex_contact_families'],['Fluid/contact families','contact_families'],['Fluid boundary families','fluid_boundary_families']]){const a=S.detail[key]||[];h+='<div class="family"><h3>'+label+' ('+a.length+')</h3><div class="muted">'+(a.length?a.slice(0,100).map(v=>esc(JSON.stringify(v))).join('<br>'):'None recorded for this formation.')+(a.length>100?'<br>…':'')+'</div></div>'}details.innerHTML=h}
function geo(raw){const f=raw?.form??raw;if(!f)return null;if(f.Circle)return['c',f.Circle.radius];if(f.Line)return['l',f.Line.length];if(f.Rectangle)return['p',[[-f.Rectangle.width/2,-f.Rectangle.height/2],[f.Rectangle.width/2,-f.Rectangle.height/2],[f.Rectangle.width/2,f.Rectangle.height/2],[-f.Rectangle.width/2,f.Rectangle.height/2]]];if(f.RegularPolygon){const n=f.RegularPolygon.sides,r=f.RegularPolygon.radius;return['p',Array.from({length:n},(_,i)=>{const a=i*2*Math.PI/n;return[r*Math.cos(a),r*Math.sin(a)]})]}if(f.Polygon)return['p',f.Polygon.vertices];if(f.Fluid&&f.Fluid.boundary)return['p',f.Fluid.boundary];if(f.Fluid)return['c',Math.sqrt(f.Fluid.nominal_area/Math.PI)];return null}
function bounds(){let a=Infinity,b=Infinity,d=-Infinity,e=-Infinity;for(const q of S.detail.formation.constituents){const g=geo(q.form),p=q.placement;if(!g)continue;const z=p.rotation_radians,co=Math.cos(z),si=Math.sin(z);if(g[0]==='c'){const r=g[1];a=Math.min(a,p.x-r);d=Math.max(d,p.x+r);b=Math.min(b,p.y-r);e=Math.max(e,p.y+r)}else if(g[0]==='l'){for(const v of [[-g[1]/2,0],[g[1]/2,0]]){const X=p.x+v[0]*co-v[1]*si,Y=p.y+v[0]*si+v[1]*co;a=Math.min(a,X);d=Math.max(d,X);b=Math.min(b,Y);e=Math.max(e,Y)}}else for(const v of g[1]){const X=p.x+v[0]*co-v[1]*si,Y=p.y+v[0]*si+v[1]*co;a=Math.min(a,X);d=Math.max(d,X);b=Math.min(b,Y);e=Math.max(e,Y)}}return[a,b,d,e]}
function fit(){const b=bounds(),w=c.clientWidth,h=c.clientHeight;if(!Number.isFinite(b[0]))return;S.zoom=Math.min((w-80)/(b[2]-b[0]||1),(h-80)/(b[3]-b[1]||1));S.pan={x:(b[0]+b[2])/2,y:(b[1]+b[3])/2}}
function P(a,b){return{x:c.clientWidth/2+(a-S.pan.x)*S.zoom,y:c.clientHeight/2-(b-S.pan.y)*S.zoom}}
function draw(){x.clearRect(0,0,c.clientWidth,c.clientHeight);x.fillStyle='#0d0d0d';x.fillRect(0,0,c.clientWidth,c.clientHeight);const f=S.detail?.formation;if(!f)return;const pal=['#5bc0eb','#f6bd60','#84a59d','#f28482','#cdb4db','#90be6d','#f7ede2'];f.constituents.forEach((a,i)=>{const g=geo(a.form),p=a.placement,s=P(p.x,p.y);if(!g)return;x.save();x.translate(s.x,s.y);x.rotate(-p.rotation_radians);x.fillStyle=pal[i%pal.length]+'33';x.strokeStyle=pal[i%pal.length];x.lineWidth=2;if(g[0]==='c'){x.beginPath();x.arc(0,0,g[1]*S.zoom,0,Math.PI*2);x.fill();x.stroke()}else if(g[0]==='l'){x.beginPath();x.moveTo(-g[1]*S.zoom/2,0);x.lineTo(g[1]*S.zoom/2,0);x.stroke()}else{x.beginPath();g[1].forEach((v,j)=>{const X=v[0]*S.zoom,Y=-v[1]*S.zoom;j?x.lineTo(X,Y):x.moveTo(X,Y)});x.closePath();x.fill();x.stroke()}x.restore();x.fillStyle='#fff';x.font='11px system-ui';x.fillText(String(i),s.x+5,s.y-5)})}
c.addEventListener('wheel',e=>{e.preventDefault();S.zoom=Math.max(.02,Math.min(1000,S.zoom*Math.exp(-e.deltaY*.001)));draw()},{passive:false});c.addEventListener('pointerdown',e=>{c.setPointerCapture(e.pointerId);S.drag={x:e.clientX,y:e.clientY,px:S.pan.x,py:S.pan.y}});c.addEventListener('pointermove',e=>{if(!S.drag)return;S.pan.x=S.drag.px-(e.clientX-S.drag.x)/S.zoom;S.pan.y=S.drag.py+(e.clientY-S.drag.y)/S.zoom;draw()});c.addEventListener('pointerup',()=>S.drag=null);addEventListener('keydown',e=>{if(e.key.toLowerCase()==='r'){fit();draw()}});document.getElementById('refresh').onclick=load;document.getElementById('prev').onclick=()=>{S.offset=Math.max(0,S.offset-S.limit);S.selected=null;load()};document.getElementById('next').onclick=()=>{if(S.offset+S.items.length>=S.total)return;S.offset+=S.limit;S.selected=null;load()};search.addEventListener('keydown',e=>{if(e.key==='Enter'){S.offset=0;load()}});size.onchange=()=>{S.offset=0;load()};setInterval(load,5000);resize();load();
})();